-- Execute only in the new recovery clone with the named fictitious identity. No retained writes.
begin;
do $$begin if not exists(select 1 from auth.users where id='52957931-04e3-4342-8122-912e95227d9c' and email='recuperacion-v336-20260911@example.invalid') then raise exception 'Solo clon ficticio';end if;end$$;
update public.datos_estudio set contenido=jsonb_set(contenido,'{0,id}','336002') where estudio_id='33600000-0000-4000-8000-000000000001' and bloque='proyectos';
update public.datos_estudio set contenido=jsonb_set(contenido,'{entries,0,pid}','336002') where estudio_id='33600000-0000-4000-8000-000000000001' and bloque='facturas';
create temp table prueba_dinero(nombre text,ok boolean);
alter table prueba_dinero enable row level security;
create policy pruebas_lectura on prueba_dinero for select to authenticated using(true);
create policy pruebas_insertar on prueba_dinero for insert to authenticated with check(true);
grant select,insert on prueba_dinero to authenticated;
select set_config('request.jwt.claims','{"sub":"52957931-04e3-4342-8122-912e95227d9c","role":"authenticated"}',true);
set local role authenticated;
do $$declare eid uuid:='33600000-0000-4000-8000-000000000001';a jsonb;r jsonb;o jsonb;again jsonb;d jsonb;cmd uuid;failed boolean;before_docs jsonb;after_docs jsonb;begin
 select contenido into before_docs from public.app_leer_bloques(eid,array['facturas']);
 a:=public.app_operaciones_accion(eid,'336002','aprobacion','{"item":"chair336"}',gen_random_uuid());
 a:=public.app_operaciones_accion(eid,'336002','aprobacion_manual',jsonb_build_object('id',a->>'id','version',a->'version','nota','Aprobacion ficticia'),gen_random_uuid());
 r:=public.app_operaciones_accion(eid,'336002','solicitud','{"items":["chair336"],"proveedor":"Proveedor ficticio"}',gen_random_uuid());
 r:=public.app_operaciones_accion(eid,'336002','oferta',jsonb_build_object('id',r->>'id','version',r->'version','precios','[60]'::jsonb),gen_random_uuid());
 o:=public.app_operaciones_accion(eid,'336002','pedido',jsonb_build_object('id',r->>'id','version',r->'version','oferta',r#>>'{contenido,ofertas,0,id}'),gen_random_uuid());
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','condiciones',jsonb_build_object('id',o->>'id','version',o->'version','tipos','[null]'::jsonb,'nota','Ensayo impuestos','transporte',0,'tipo_transporte',0,'retencion',0),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('impuesto_desconocido_no_es_cero',failed);
 o:=public.app_pedido_economia(eid,'336002','condiciones',jsonb_build_object('id',o->>'id','version',o->'version','tipos','[21]'::jsonb,'nota','Ensayo impuestos','transporte',0,'tipo_transporte',0,'retencion',0),gen_random_uuid());
 insert into prueba_dinero values('total_decimal',o#>>'{contenido,economia,total}'='145.20' and (o#>>'{contenido,economia,impuestos}')::numeric=25.2);
 o:=public.app_operaciones_accion(eid,'336002','confirmar',jsonb_build_object('id',o->>'id','version',o->'version'),gen_random_uuid());
 d:=jsonb_build_object('id',o->>'id','version',o->'version','importe',50,'fecha',current_date,'nota','Pago ficticio');cmd:=gen_random_uuid();
 o:=public.app_pedido_economia(eid,'336002','pago',d,cmd);again:=public.app_pedido_economia(eid,'336002','pago',d,cmd);
 insert into prueba_dinero values('reintento_no_duplica',o=again and jsonb_array_length(o#>'{contenido,pagos}')=1),('pago_parcial',(o#>>'{contenido,saldos,pendiente}')::numeric=95.2);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','pago',d,gen_random_uuid());exception when sqlstate 'PT409' then failed:=true;end;insert into prueba_dinero values('version_antigua_rechazada',failed);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','pago',d||jsonb_build_object('version',o->'version','importe',100),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('sobrepago_rechazado',failed);
 o:=public.app_pedido_economia(eid,'336002','pago',d||jsonb_build_object('version',o->'version','importe',95.2),gen_random_uuid());
 insert into prueba_dinero values('pagado_total',(o#>>'{contenido,saldos,pendiente}')::numeric=0);
 o:=public.app_operaciones_accion(eid,'336002','recibir',jsonb_build_object('id',o->>'id','version',o->'version','cantidades','[2]'::jsonb),gen_random_uuid());
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','devolver',jsonb_build_object('id',o->>'id','version',o->'version','cantidades','[3]'::jsonb,'nota','Devolucion ficticia'),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('devolucion_excesiva_rechazada',failed);
 o:=public.app_pedido_economia(eid,'336002','devolver',jsonb_build_object('id',o->>'id','version',o->'version','cantidades','[1]'::jsonb,'nota','Devolucion ficticia'),gen_random_uuid());
 insert into prueba_dinero values('devolucion_sin_reintegro_automatico',o->>'estado'='parcial' and (o#>>'{contenido,saldos,reintegrado}')::numeric=0 and (o#>>'{contenido,saldos,abonado}')::numeric=0);
 o:=public.app_pedido_economia(eid,'336002','abono',d||jsonb_build_object('version',o->'version','importe',72.6),gen_random_uuid());
 insert into prueba_dinero values('abono_genera_saldo_a_recuperar',(o#>>'{contenido,saldos,a_recuperar}')::numeric=72.6);
 o:=public.app_pedido_economia(eid,'336002','reintegro',d||jsonb_build_object('version',o->'version','importe',72.6),gen_random_uuid());
 insert into prueba_dinero values('reintegro_concilia',(o#>>'{contenido,saldos,a_recuperar}')::numeric=0 and (o#>>'{contenido,saldos,pendiente}')::numeric=0);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','reintegro',d||jsonb_build_object('version',o->'version','importe',1),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('reintegro_excesivo_rechazado',failed);
 o:=public.app_operaciones_accion(eid,'336002','recibir',jsonb_build_object('id',o->>'id','version',o->'version','cantidades','[1]'::jsonb),gen_random_uuid());
 insert into prueba_dinero values('reposicion_tras_devolucion',o->>'estado'='recibido' and (o#>>'{contenido,lineas,0,recibido}')::numeric=3 and (o#>>'{contenido,lineas,0,devuelto}')::numeric=1);
 o:=public.app_pedido_economia(eid,'336002','vincular_factura',jsonb_build_object('id',o->>'id','version',o->'version','asiento',336101,'nota','Vinculo ficticio'),gen_random_uuid());
 select contenido into after_docs from public.app_leer_bloques(eid,array['facturas']);
 insert into prueba_dinero values('contabilidad_intacta',before_docs=after_docs),('factura_vinculada',jsonb_array_length(o#>'{contenido,facturas}')=1);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','vincular_factura',jsonb_build_object('id',o->>'id','version',o->'version','asiento',336101,'nota','Vinculo ficticio'),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('sin_vinculo_duplicado',failed);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','condiciones',jsonb_build_object('id',o->>'id','version',o->'version','tipos','[0]'::jsonb,'nota','Cambio ficticio','transporte',0,'tipo_transporte',0,'retencion',0),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('importe_confirmado_inmutable',failed);
 insert into prueba_dinero values('historial_preservado',jsonb_array_length(public.app_operaciones_historial(eid,(o->>'id')::uuid))>=10);

 failed:=false;begin perform public.app_pedido_economia(eid,'336002','pago',d||jsonb_build_object('version',o->'version','importe',0.001),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('precision_monetaria_rechazada',failed);
 failed:=false;begin perform public.app_pedido_economia(eid,'336002','abono',d||jsonb_build_object('version',o->'version','importe',1,'fecha',current_date+1),gen_random_uuid());exception when others then failed:=true;end;insert into prueba_dinero values('fecha_futura_rechazada',failed);
 o:=public.app_pedido_economia(eid,'336002','anular_abono',jsonb_build_object('id',o->>'id','version',o->'version','movimiento',o#>>'{contenido,abonos,0,id}','nota','Correccion ficticia'),gen_random_uuid());
 insert into prueba_dinero values('anular_abono_conserva_historial',(o#>>'{contenido,abonos,0,anulado}')::boolean and (o#>>'{contenido,saldos,pendiente}')::numeric=72.6);
 o:=public.app_pedido_economia(eid,'336002','anular_pago',jsonb_build_object('id',o->>'id','version',o->'version','movimiento',o#>>'{contenido,pagos,2,id}','nota','Correccion reintegro'),gen_random_uuid());
 insert into prueba_dinero values('anular_reintegro_recalcula',(o#>>'{contenido,saldos,pendiente}')::numeric=0 and (o#>>'{contenido,pagos,2,anulado}')::boolean);
 r:=public.app_operaciones_accion(eid,'336002','solicitud','{"items":["chair336"],"proveedor":"Proveedor ficticio"}',gen_random_uuid());
 r:=public.app_operaciones_accion(eid,'336002','oferta',jsonb_build_object('id',r->>'id','version',r->'version','precios','[60]'::jsonb),gen_random_uuid());
 o:=public.app_operaciones_accion(eid,'336002','pedido',jsonb_build_object('id',r->>'id','version',r->'version','oferta',r#>>'{contenido,ofertas,0,id}'),gen_random_uuid());
 o:=public.app_pedido_economia(eid,'336002','condiciones',jsonb_build_object('id',o->>'id','version',o->'version','tipos','[0]'::jsonb,'nota','Ensayo transporte y retencion','transporte',10,'tipo_transporte',10,'retencion',5),gen_random_uuid());
 insert into prueba_dinero values('cero_transporte_retencion',(o#>>'{contenido,economia,total}')::numeric=124.5);
end$$;
reset role;
update public.miembros set rol='miembro' where estudio_id='33600000-0000-4000-8000-000000000001' and user_id='52957931-04e3-4342-8122-912e95227d9c';
set local role authenticated;
do $$declare failed boolean:=false;begin
 begin perform public.app_pedido_economia('33600000-0000-4000-8000-000000000001','336002','pago','{}',gen_random_uuid());exception when insufficient_privilege then failed:=true;end;
 insert into prueba_dinero values('colaborador_no_registra_pagos',failed);
end$$;
reset role;
insert into prueba_dinero values('anon_sin_rpc',not has_function_privilege('anon','public.app_pedido_economia(uuid,text,text,jsonb,uuid)','EXECUTE'));
select count(*) as pruebas,bool_and(ok) as todas_correctas,jsonb_agg(nombre) filter(where not ok) as fallos from prueba_dinero;
rollback;
