import {build} from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const target=path.resolve(here,'../../supabase/functions/product-clipper');
const result=await build({absWorkingDir:here,entryPoints:['vendor-entry.mjs'],bundle:true,platform:'node',format:'esm',external:['canvas'],outfile:path.join(target,'vendor.mjs'),metafile:true});
const packages=new Map();
for(const input of Object.keys(result.metafile.inputs)){
 if(!input.includes('node_modules'))continue;
 let folder=path.dirname(path.resolve(here,input));
 while(folder!==path.dirname(folder)){
  try{const meta=JSON.parse(await fs.readFile(path.join(folder,'package.json'),'utf8'));if(meta.name){packages.set(meta.name,{folder,version:meta.version});break;}}catch{}
  folder=path.dirname(folder);
 }
}
let notices='# Product Clipper bundled third-party licenses\n\nGenerated by tools/product-clipper/build-vendor.mjs.\n';
for(const [name,{folder,version}] of [...packages].sort()){
 const files=(await fs.readdir(folder)).filter(n=>/^(licen[sc]e|copying|notice)(\.|$)/i.test(n));
 if(!files.length)throw Error('License missing for '+name);
 notices+='\n## '+name+' '+version+'\n';
 for(const file of files)notices+='\n'+await fs.readFile(path.join(folder,file),'utf8')+'\n';
}
const normalize=s=>s.replace(/[ \t]+$/gm,'').trimEnd()+'\n';
await fs.writeFile(path.join(target,'THIRD-PARTY-LICENSES.txt'),normalize(notices));
const bundle=path.join(target,'vendor.mjs');await fs.writeFile(bundle,normalize(await fs.readFile(bundle,'utf8')));
console.log('Built vendor and licenses for '+packages.size+' packages.');
