/* Catalog presentation; all writes use the existing study config transaction. */
const CatalogUI=(()=>{
 const E=x=>ModernoDaily.escape(String(x??''));
 let editing=null,picking=null;
 function openPicker(){picking={draft:state.draft,study:ESTUDIO_ID,catalog:JSON.stringify(state.catalog)};pickerDraw();}
 function pickerCurrent(){if(!picking||!state.draft||picking.draft!==state.draft||picking.study!==ESTUDIO_ID||picking.catalog!==JSON.stringify(state.catalog)){toast('El documento o catálogo cambió. Cierra y vuelve a abrir el selector');return false;}return true;}
 let seedBusy=false;const seedSeen=new Set();
 async function trySeed(){
  if(seedBusy||!sb||_accessRole!=='admin'||!ESTUDIO_ID||_cloudBusy||seedSeen.has(ESTUDIO_ID)||!_cloudSeen.config||_cloudHash.config!==canon(CLOUD_BLOCKS.config.get()))return;
  const study=ESTUDIO_ID;seedBusy=true;
  try{
   const {data,error}=await sb.rpc('app_catalogo_inicial',{p_estudio:study,p_base:_cloudSeen.config});if(error)throw error;
   if(ESTUDIO_ID!==study)return;
   if(data?.status==='initialized'){cloudApplyRemote('config',data.contenido,data.updated_at);seedSeen.add(study);}
   else if(['existing_study','already_initialized','custom_catalog','locale_unavailable'].includes(data?.status))seedSeen.add(study);
  }catch(e){console.warn('[catalog]',e.message||'No se pudo comprobar el catálogo inicial');}finally{seedBusy=false;}
 }
 const canEdit=()=>_accessRole==='admin';
 const requireAdmin=()=>{if(!canEdit()){toast('Solo un administrador puede modificar el catálogo');return false;}return true;};
 const money=c=>c.price==null?'Por medir':fmt(c.price);
 const persist=()=>{persistNow();cloudDirty();render();};
 const delIcon=()=>'<svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M18 6l-12 12"/><path d="M6 6l12 12"/></svg>';
 function query(picker=false){return ModernoCatalog.search(picker?state.catalog:byBrand(state.catalog),{q:picker?state.catQ:state.catSearch,family:picker?state.catPickFamily:state.catCat,type:picker?state.catPickType:state.catType,view:picker?(state.catPickView||'usual'):(state.catListView||'usual'),brand:picker?state.catTab:undefined});}
 function focus(id){setTimeout(()=>{const e=document.getElementById(id);if(e){e.focus();e.setSelectionRange(e.value.length,e.value.length);}},0);}
 function filter(key,value,picker=false){state[key]=value;state.catPage=0;if(picker)pickerDraw();else render();if(key==='catSearch'||key==='catQ')focus(picker?'catalogPickerSearch':'catalogSearch');}
 function filters(picker=false){
  const key=picker?'catQ':'catSearch',family=picker?'catPickFamily':'catCat',type=picker?'catPickType':'catType',view=picker?'catPickView':'catListView';
  const families=[...new Set((state.catalog||[]).filter(c=>!c.archived&&c.tipo!=='Producto').map(c=>c.cat).filter(Boolean))].sort();
  return `<div class="catalog-filters"><input id="${picker?'catalogPickerSearch':'catalogSearch'}" aria-label="Buscar en el catálogo" style="flex:1;min-width:190px" placeholder="Nombre, código o sinónimo…" value="${E(state[key])}" oninput="CatalogUI.filter('${key}',this.value,${picker})"><select aria-label="Familia" style="max-width:230px" onchange="CatalogUI.filter('${family}',this.value,${picker})"><option value="">Todas las familias</option>${families.map(f=>`<option ${state[family]===f?'selected':''}>${E(f)}</option>`).join('')}</select><select aria-label="Tipo" style="max-width:175px" onchange="CatalogUI.filter('${type}',this.value,${picker})">${[['','Todos los tipos'],['Servicio','Servicios'],['Partida','Partidas de obra']].map(([v,n])=>`<option value="${v}" ${state[type]===v?'selected':''}>${n}</option>`).join('')}</select><select aria-label="Frecuencia" style="max-width:165px" onchange="CatalogUI.filter('${view}',this.value,${picker})">${[['usual','Habituales'],['all','Todas'],['extras','Extras']].map(([v,n])=>`<option value="${v}" ${(state[view]||'usual')===v?'selected':''}>${n}</option>`).join('')}</select></div>`;
 }
 const familyTone=c=>['Carpintería de madera','Carpintería metálica y vidrio','Climatización','Electricidad','Fontanería','Interiorismo','Obra','Pintura y remates'].indexOf(c.cat);
 function layout(value){if(!['cards','list'].includes(value))return;state.catLayout=value;render();}
 function layoutSwitch(){const current=state.catLayout==='list'?'list':'cards';return `<div class="catalog-view-switch" role="group" aria-label="Vista del catálogo">${[['cards','Tarjetas','crop-1-1'],['list','Lista','list']].map(([value,label,icon])=>`<button type="button" aria-label="Vista de ${label.toLowerCase()}" title="${label}" aria-pressed="${current===value}" onclick="CatalogUI.layout('${value}')"><span class="catalog-view-icon catalog-view-${icon}" aria-hidden="true"></span></button>`).join('')}</div>`;}
 function view(){
  const all=query(),size=24,page=Math.max(0,Math.min(state.catPage||0,Math.ceil(all.length/size)-1)),items=all.slice(page*size,page*size+size);
  return `<section class="catalog-board"><header class="catalog-heading"><div><span class="catalog-eyebrow">IDEAS QUE TOMAN FORMA</span><h1 class="big">Tu <span class="hl">catálogo</span></h1><p class="sub">Todo lo que necesitas para dar forma a tu próximo presupuesto.</p></div>${canEdit()?'<button class="btn btn-dark" onclick="catalogModal()">＋ Nueva partida</button>':''}</header>${filters()}<div class="catalog-summary"><span>${all.length} ${all.length===1?'partida':'partidas'}</span><span class="catalog-tax-note">Precios base sin impuestos</span>${layoutSwitch()}</div><div class="catalog-grid ${state.catLayout==='list'?'catalog-list':''}">${items.map(c=>`<article class="catalog-card catalog-tone-${familyTone(c)}"><div class="catalog-card-top"><span class="catalog-family">${E(c.cat||'Sin familia')}</span><small>${E(c.tipo||'Servicio')}</small></div><small class="catalog-code">${E(c.code)}</small><h2>${E(c.name)}</h2><p class="catalog-subcategory">${E(c.subcat||'')}</p><footer><div class="catalog-price"><strong>${money(c)}</strong><span>/ ${E(unitLabel(c.unit))}${c.priceStatus==='orientativo'?' · Orientativo':''}</span></div>${canEdit()?`<div class="catalog-actions"><button class="btn btn-ghost" title="Editar partida" aria-label="Editar partida" onclick="catEdit(${c.id})">${ico('editar')}</button><button class="btn btn-ghost" title="Duplicar partida" aria-label="Duplicar partida" onclick="catDup(${c.id})">${ico('copiar')}</button><button class="btn btn-ghost" title="Eliminar" aria-label="Eliminar" onclick="catDel(${c.id})">${delIcon()}</button></div>`:''}</footer></article>`).join('')}</div>${!items.length?'<div class="empty">No hay partidas con estos filtros. Prueba con «Todas».</div>':''}${all.length>size?`<nav class="catalog-pagination" aria-label="Páginas del catálogo"><button class="btn btn-ghost" ${page===0?'disabled':''} onclick="state.catPage=${page-1};render()">Anterior</button><span>${page+1} / ${Math.ceil(all.length/size)}</span><button class="btn btn-ghost" ${(page+1)*size>=all.length?'disabled':''} onclick="state.catPage=${page+1};render()">Siguiente</button></nav>`:''}</section>`;
 }
 function remove(id){if(!requireAdmin())return;const c=state.catalog.find(x=>x.id===id),study=ESTUDIO_ID,before=JSON.stringify(c);if(!c||c.archived)return;askConfirm(`¿Eliminar «${c.name}» del catálogo? Sus líneas en documentos antiguos se conservarán.`, 'Eliminar',()=>{if(!requireAdmin())return;const current=state.catalog.find(x=>x.id===id);if(study!==ESTUDIO_ID||JSON.stringify(current)!==before){toast('El catálogo cambió; vuelve a revisar la partida');return;}state.catalogArchive=state.catalogArchive||[];if(!state.catalogArchive.some(x=>x.id===id))state.catalogArchive.push(JSON.parse(JSON.stringify(c)));state.catalog=state.catalog.map(x=>x.id===id?{...x,archived:true}:x);persist();});}
 function duplicate(id){if(!requireAdmin())return;const c=state.catalog.find(x=>x.id===id);if(!c)return;let next=Date.now();while(state.catalog.some(x=>x.id===next))next++;state.catalog.push({...JSON.parse(JSON.stringify(c)),id:next,code:'',name:c.name+' (copia)'});persist();}
 function edit(id=null){
  if(!requireAdmin())return;const c=id===null?null:state.catalog.find(x=>x.id===id);if(id!==null&&!c)return;editing={id,before:JSON.stringify(c),study:ESTUDIO_ID};
  modal(`<h3>${c?'Editar partida':'Nueva partida'}</h3><label>Nombre</label><input id="ceN" value="${E(c?.name)}">${catCatField('ceC',c?.cat||'')}${unitPills('ceU',c?.unit||'ud')}<label>Alcance y condiciones</label><textarea id="ceD" rows="6">${E(c?.desc)}</textarea><div class="row2"><div><label>Precio base sin impuestos (€)</label><input id="ceP" type="number" min="0" step="0.01" value="${c?.price??''}" placeholder="Vacío: por medir"></div><div><label>Coste interno (€)</label><input id="ceK" type="number" min="0" step="0.01" value="${c?.cost??''}" placeholder="Sin coste conocido"></div></div><label>Tipo</label><select id="ceT"><option value="Partida" ${c?.tipo==='Partida'?'selected':''}>Partida de obra</option><option value="Servicio" ${c?.tipo==='Servicio'?'selected':''}>Servicio</option></select><div class="modal-foot"><button class="btn btn-ghost" onclick="closeModal()">Cancelar</button><button class="btn btn-dark" onclick="CatalogUI.saveItem()">Guardar</button></div>`);pills('ceU');
 }
 function saveItem(){
  if(!requireAdmin()||!editing)return;const {id,before,study}=editing,c=id===null?null:state.catalog.find(x=>x.id===id);
  if(study!==ESTUDIO_ID||JSON.stringify(c??null)!==before){toast('Esta partida cambió. Cierra y vuelve a abrirla para revisar la última versión');return;}
  const get=id=>document.getElementById(id).value,name=get('ceN').trim(),p=get('ceP'),k=get('ceK');
  if(!name||[p,k].some(v=>v!==''&&(!Number.isFinite(+v)||+v<0))){toast('Completa el nombre y revisa los importes');return;}
  let next=id??Date.now();while(id===null&&state.catalog.some(x=>x.id===next))next++;
  const updated={...c,id:next,brand:c?.brand||(state.brandFilter!=='all'&&state.brandFilter)||wsOrder[0],name,cat:get('ceC').trim(),desc:get('ceD').trim(),unit:document.querySelector('#ceU .on')?.dataset.v||'ud',price:p===''?null:+p,cost:k===''?null:+k,tipo:get('ceT'),priceStatus:p===''?'medicion':'personalizado',priceRange:null};
  if(c){state.catalogArchive=state.catalogArchive||[];if(!state.catalogArchive.some(x=>x.id===id))state.catalogArchive.push(JSON.parse(JSON.stringify(c)));state.catalog[state.catalog.indexOf(c)]=updated;}else state.catalog.push(updated);editing=null;closeModal();persist();
 }
 function pickerDraw(){
  const items=query(true);
  modal(`<h3>Añadir del catálogo</h3><p>Precios base sin impuestos. Revisa el alcance antes de añadir una partida.</p>${filters(true)}<div style="max-height:48vh;overflow:auto">${items.slice(0,100).map(c=>`<div class="catalog-item catpick ${(state._catSel||{})[c.id]?'sel':''}" style="gap:10px"><button class="btn btn-ghost" aria-label="Seleccionar partida" onclick="${c.price==null?`CatalogUI.pickOne(${c.id})`:`catPickToggle(${c.id},this.parentElement)`}">${(state._catSel||{})[c.id]?'✓':'＋'}</button><span style="flex:1;min-width:0"><small>${E(c.code)} · ${E(c.cat)}</small><br>${E(c.name)}</span><span style="white-space:nowrap">${money(c)} / ${E(unitLabel(c.unit))}</span><button class="btn btn-ghost" onclick="CatalogUI.pickOne(${c.id})">Detalle</button></div>`).join('')}${items.length>100?'<p>Se muestran 100 resultados. Concreta la búsqueda para ver el resto.</p>':''}${!items.length?'<p>No hay resultados. Prueba con «Todas».</p>':''}</div><p id="catPickN"></p><div class="modal-foot"><button class="btn btn-ghost" onclick="state._catSel={};closeModal()">Cancelar</button><button class="btn btn-dark" id="catPickAdd" onclick="catPickAddAll()">Añadir seleccionadas</button></div>`);catPickCount();
 }
 function add(){if(!pickerCurrent())return;try{const selected=new Set(Object.keys(state._catSel||{}).map(Number));const lines=state.catalog.filter(c=>selected.has(c.id)).map(c=>ModernoCatalog.line(c));if(!lines.length)return;state.draft.lines.push(...lines);state._catSel={};closeModal();render();}catch(e){toast(e.message);}}
 function pickOne(id,variant=''){
  if(!pickerCurrent())return;
  const c=state.catalog.find(x=>x.id===id);if(!c)return;const v=(c.variants||[]).find(x=>x.code===variant),p=v?v.price:c.price;
  modal(`<h3>${E(c.name)}</h3>${c.variants?.length?`<label>Alcance</label><select onchange="CatalogUI.pickOne(${id},this.value)"><option value="">${E(c.code)} · Principal</option>${c.variants.map(v=>`<option value="${E(v.code)}" ${variant===v.code?'selected':''}>${E(v.code)} · ${E(v.name)}</option>`).join('')}</select>`:''}<p style="white-space:pre-line;max-height:40vh;overflow:auto">${E(v?.desc||c.desc)}</p><label>Precio unitario sin impuestos · ${E(unitLabel(c.unit))}</label><input id="catOnePrice" type="number" min="0" step="0.01" value="${p??''}" placeholder="Introduce el precio tras medir"><div class="modal-foot"><button class="btn btn-ghost" onclick="catPickDraw()">Volver</button><button class="btn btn-dark" onclick="CatalogUI.addOne(${id},'${E(variant)}')">Añadir al documento</button></div>`);
 }
 function addOne(id,variant){if(!pickerCurrent())return;try{const raw=document.getElementById('catOnePrice').value;if(raw==='')throw Error('Introduce un precio tras medir el alcance');const c=state.catalog.find(x=>x.id===id);state.draft.lines.push(ModernoCatalog.line(c,{unitPrice:+raw,variantCode:variant||undefined}));closeModal();render();}catch(e){toast(e.message);}}
 function addId(id){try{state.draft.lines.push(ModernoCatalog.line(state.catalog.find(x=>x.id===id)));render();}catch(e){toast(e.message);}}
 function saveLine(i){
  const draft=state.draft,study=ESTUDIO_ID,old=draft?.lines[i];if(!old)return;const get=id=>document.getElementById(id).value,p=get('leP'),q=get('leQ'),k=get('leK');
  if(!get('leN').trim()||p===''||q===''||[p,q,k].some(v=>v!==''&&(!Number.isFinite(+v)||+v<0))){toast('Completa concepto, cantidad y precio válidos');return;}
  const l={...old,name:get('leN').trim(),desc:get('leD').trim(),cap:get('leC').trim(),price:+p,qty:+q,unit:get('leU'),cost:k===''?null:+k,provider:get('leV').trim()};delete l.catalogPriceIntent;
  const finish=intent=>{if(ESTUDIO_ID!==study||state.draft!==draft||draft.lines[i]!==old){toast('El documento cambió; vuelve a abrir la línea');return;}if(intent)l.catalogPriceIntent=intent;draft.lines[i]=l;closeModal();render();};
  const c=state.catalog.find(x=>x.id===l.catId),changed=old.price!==l.price;
  if(!changed||!c||!canEdit()||(state.draft.kind==='factura'&&state.draft.editRef)){finish(!changed&&old.unit===l.unit?old.catalogPriceIntent:undefined);return;}
  let intent,error;try{intent=ModernoCatalog.priceIntent(l,c,l.price,l.unit,{role:_accessRole,studyId:ESTUDIO_ID});}catch(e){error=e.message;}
  modal(`<h3>¿Dónde aplicar este precio?</h3><p><b>${E(c.name)}</b></p><p>Catálogo: ${money(c)} / ${E(unitLabel(c.unit))}<br>Nuevo precio: ${fmt(l.price)} / ${E(unitLabel(l.unit))}</p><p>Se aplicará al catálogo cuando guardes el documento. Los demás documentos conservarán sus importes.</p>${error?`<p>${E(error)}</p>`:''}<div class="modal-foot"><button class="btn btn-ghost" id="catPriceOnly">Solo este documento</button>${intent?'<button class="btn btn-dark" id="catPriceStudy">Actualizar catálogo del estudio</button>':''}</div>`);
  document.getElementById('catPriceOnly').onclick=()=>finish();if(intent)document.getElementById('catPriceStudy').onclick=()=>finish(intent);
 }
 return {view,layout,filter,remove,duplicate,edit,saveItem,openPicker,picker:pickerDraw,add,pickOne,addOne,addId,saveLine,trySeed};
})();
