/* Server-authoritative purchase amounts. Recording a payment never initiates a transfer. */
var PurchaseFinance=(()=>{
 let current=null;
 const E=v=>ModernoDaily.escape(v??'');
 const field=id=>document.getElementById(id).value.trim();
 const number=id=>{const raw=field(id),n=Number(raw);if(!raw||!Number.isFinite(n)||n<0)throw Error('Completa los importes y cantidades; indica cero cuando corresponda');return n;};
 const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
 function shell(body,submit,label='Guardar registro'){
  document.getElementById('opsBody').innerHTML=`<div class="ops-head"><h3>Economía del pedido</h3><button class="btn btn-ghost" onclick="ProductOps.redraw()">Volver a pedidos</button></div>${body}${submit?`<label>Detalle para el historial<textarea id="pmNote" rows="3" maxlength="2000" placeholder="Referencia y motivo del registro"></textarea></label><div class="ops-actions"><button class="btn btn-ghost" onclick="PurchaseFinance.open('${current.id}')">Cancelar</button><button class="btn btn-dark" onclick="${submit}">${label}</button></div>`:''}`;
  try{syncRefresh();}catch(e){}
 }
 function open(id){current=ProductOps.getRecord(id);if(!current)return;const c=current.contenido,s=c.saldos,confirmed=['confirmado','parcial','recibido'].includes(current.estado);
  shell(`<p>${E(c.proveedor)} · ${E(id.slice(0,8).toUpperCase())}</p>${s?`<div class="pm-totals">${[['Total del pedido',s.total],['Abonos',s.abonado],['Pagos registrados',s.pagado],['Reintegros recibidos',s.reintegrado],['Pendiente de pago',s.pendiente],['A recuperar del proveedor',s.a_recuperar]].map(([label,value])=>`<div><small>${label}</small><b>${fmt(value)}</b></div>`).join('')}</div>`:'<p>Este pedido todavía no tiene impuestos revisados. Sus precios originales se conservan.</p>'}
  <div class="ops-actions">${!c.economia||current.estado==='borrador'?'<button class="btn btn-ghost" onclick="PurchaseFinance.conditions()">Revisar importes e impuestos</button>':''}${confirmed&&s?`<button class="btn btn-dark" onclick="PurchaseFinance.movement('pago')" ${s.pendiente<=0?'disabled':''}>Registrar pago</button><button class="btn btn-ghost" onclick="PurchaseFinance.movement('reintegro')" ${s.a_recuperar<=0?'disabled':''}>Registrar reintegro</button><button class="btn btn-ghost" onclick="PurchaseFinance.returns()">Registrar devolución</button><button class="btn btn-ghost" onclick="PurchaseFinance.movement('abono')">Registrar abono</button><button class="btn btn-ghost" onclick="PurchaseFinance.invoice()">Vincular factura</button>`:''}</div>
  <p class="pm-hint">Los pagos reflejan movimientos ya realizados por tu equipo. Registrar una recepción, devolución o factura no registra un pago ni modifica Contabilidad.</p>
  <h4>Movimientos</h4>${(c.pagos||[]).map(m=>`<article class="ops-card"><b>${m.tipo==='pago'?'Pago':'Reintegro'} · ${fmt(m.importe)}${m.anulado?' · Anulado':''}</b><small>${E(m.fecha)}</small><p>${E(m.nota)}</p>${!m.anulado?`<button class="btn btn-ghost" onclick="PurchaseFinance.unlink('anular_pago','${m.id}')">Anular registro erróneo</button>`:''}</article>`).join('')||'<p>No hay movimientos registrados.</p>'}
  <h4>Abonos del proveedor</h4>${(c.abonos||[]).map(m=>`<article class="ops-card"><b>${fmt(m.importe)}${m.anulado?' · Anulado':''}</b><small>${E(m.fecha)}</small><p>${E(m.nota)}</p>${!m.anulado?`<button class="btn btn-ghost" onclick="PurchaseFinance.unlink('anular_abono','${m.id}')">Anular abono erróneo</button>`:''}</article>`).join('')||'<p>Sin abonos registrados. Una devolución física no implica que el proveedor haya aceptado un abono.</p>'}
  <h4>Facturas vinculadas</h4>${(c.facturas||[]).map(m=>`<article class="ops-card"><b>${E(m.referencia)} · ${fmt(m.importe)}${m.retirado?' · Vínculo retirado':''}</b><p>${E(m.proveedor)} · ${E(m.fecha)}</p><small>Datos conservados al vincular. El documento contable original mantiene su propio estado.</small>${!m.retirado?`<button class="btn btn-ghost" onclick="PurchaseFinance.unlink('desvincular_factura','${m.id}')">Retirar vínculo</button>`:''}</article>`).join('')||'<p>Sin facturas vinculadas.</p>'}
  <button class="btn btn-ghost" onclick="ProductOps.history('${id}')">Ver historial completo</button>`);
 }
 function conditions(){const c=current.contenido,e=c.economia;
  shell(`<p>Importes de compra en euros. Indica el impuesto real de cada línea; no se asigna un tipo por defecto. El total se calcula en el servidor, redondeando cada línea a dos decimales.</p>${c.lineas.map((l,i)=>`<label>${E(l.snapshot.name)} · ${E(l.qty)} × ${fmt(l.precio)}<span>Impuesto (%)</span><input id="pmTax${i}" type="number" min="0" max="100" step="0.01" value="${E(e?.lineas?.[i]?.tipo??'')}"></label>`).join('')}<div class="pm-grid"><label>Transporte sin impuestos (€)<input id="pmTransport" type="number" min="0" step="0.01" value="${E(e?.transporte??0)}"></label><label>Impuesto del transporte (%)<input id="pmTransportTax" type="number" min="0" max="100" step="0.01" value="${E(e?.tipo_transporte??0)}"></label><label>Retención sobre la base (%)<input id="pmRetention" type="number" min="0" max="100" step="0.01" value="${E(e?.tipo_retencion??0)}"></label></div>`,'PurchaseFinance.saveConditions()','Guardar importes revisados');
 }
 async function saveConditions(){try{await save('condiciones',{tipos:current.contenido.lineas.map((_,i)=>number('pmTax'+i)),transporte:number('pmTransport'),tipo_transporte:number('pmTransportTax'),retencion:number('pmRetention')});}catch(e){toast(e.message);}}
 function movement(kind){const s=current.contenido.saldos;const names={pago:'Pago ya realizado',reintegro:'Reintegro recibido del proveedor',abono:'Abono aceptado por el proveedor'};
  shell(`<h4>${names[kind]}</h4><p>${kind==='abono'?'Reduce el importe pendiente; no significa que el proveedor haya devuelto dinero. Indica la referencia de su abono.':kind==='pago'?'Registra únicamente un pago que ya hayas realizado. No se envía dinero desde la app.':'Registra únicamente dinero que el proveedor ya haya devuelto.'}</p><div class="pm-grid"><label>Importe (€)<input id="pmAmount" type="number" min="0.01" step="0.01" max="${E(kind==='pago'?s.pendiente:kind==='reintegro'?s.a_recuperar:s.total-s.abonado)}"></label><label>Fecha real<input id="pmDate" type="date" max="${today()}" value="${today()}"></label></div>`,`PurchaseFinance.saveMovement('${kind}')`);
 }
 async function saveMovement(kind){try{await save(kind,{importe:number('pmAmount'),fecha:field('pmDate')});}catch(e){toast(e.message);}}
 function returns(){shell(`<p>Indica las unidades entregadas de vuelta al proveedor. El abono y el reintegro se registran por separado cuando se produzcan.</p>${current.contenido.lineas.map((l,i)=>`<label>${E(l.snapshot.name)} · disponibles para devolver ${E((l.recibido||0)-(l.devuelto||0))}<input id="pmQty${i}" type="number" min="0" max="${E((l.recibido||0)-(l.devuelto||0))}" step="0.01" value="0"></label>`).join('')}`,'PurchaseFinance.saveReturn()','Registrar devolución');}
 async function saveReturn(){try{await save('devolver',{cantidades:current.contenido.lineas.map((_,i)=>number('pmQty'+i))});}catch(e){toast(e.message);}}
 let invoices=[];
 function invoice(){invoices=(state.entries||[]).filter(e=>e.kind==='out'&&(!e.pid||String(e.pid)===String(current.proyecto_id))&&!(state.entriesDel||{})[String(e.id)]);
  shell(`<p>Selecciona la factura o gasto del proveedor que corresponde a este pedido. Se conserva una referencia; su importe y su estado contable no se modifican.</p><label>Factura de proveedor<select id="pmInvoice"><option value="">Seleccionar…</option>${invoices.map((e,i)=>`<option value="${i}">${E(e.concept)} · ${E(e.sup||'Sin proveedor')} · ${fmt(e.amount)}</option>`).join('')}</select></label>`,'PurchaseFinance.saveInvoice()','Vincular factura');
 }
 async function saveInvoice(){try{const v=field('pmInvoice');if(v===''||!invoices[+v])throw Error('Selecciona una factura');await save('vincular_factura',{asiento:invoices[+v].id});}catch(e){toast(e.message);}}
 function unlink(kind,id){shell(`<p>${kind.startsWith('anular_')?'Anular el registro de un movimiento no revierte ninguna transferencia bancaria. Su historial se conserva.':'Retirar el vínculo no borra la factura ni modifica Contabilidad.'}</p>`,`PurchaseFinance.saveUnlink('${kind}','${id}')`,'Registrar corrección');}
 async function saveUnlink(kind,id){await save(kind,kind.startsWith('anular_')?{movimiento:id}:{vinculo:id});}
 async function save(kind,data){const nota=field('pmNote');if(nota.length<5){toast('Añade una referencia o motivo para el historial');return;}const id=current.id;const r=await ProductOps.money(kind,{id,version:current.version,...data,nota});if(r)open(id);}
 return {open,conditions,saveConditions,movement,saveMovement,returns,saveReturn,invoice,saveInvoice,unlink,saveUnlink};
})();
