/* Presentation helpers: existing write paths and permissions remain authoritative. */
const WorkflowPolish=(()=>{
 let motion=null,localMotion=false;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
 function change(update,direction=0){
  const focused=document.activeElement,focusText=focused?.textContent,focusLabel=focused?.getAttribute('aria-label');
  if(motion)motion.cancel();localMotion=true;try{update();render();}finally{localMotion=false;}
  const candidates=[...V.querySelectorAll('button,select')];const next=candidates.find(el=>focusLabel?el.getAttribute('aria-label')===focusLabel:focusText&&el.textContent===focusText);next?.focus({preventScroll:true});
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&V.animate)motion=V.animate([{opacity:0,transform:direction?'translateX('+direction*28+'px)':'none'},{opacity:1,transform:'none'}],{duration:260,easing:'cubic-bezier(.22,.61,.36,1)'});
 }
 const categoryOrder=names=>{const ordered=state.account?.libraryCategoryOrder||[];return [...new Set([...ordered.filter(n=>names.includes(n)),...names.slice().sort((a,b)=>a.localeCompare(b,'es'))])];};
 function categoryNames(){return categoryOrder([...new Set([...(state.customCats||[]),...state.library.map(x=>x.cat||'Otros')])]);}
 function categoryMove(name,target){if(_accessRole!=='admin')return;const names=categoryNames(),from=names.indexOf(name);if(from<0||target<0||target>=names.length)return;names.splice(from,1);names.splice(target,0,name);state.account.libraryCategoryOrder=names;persistSoon();render();[...V.querySelectorAll('[data-category]')].find(el=>el.dataset.category===name)?.querySelector('button')?.focus({preventScroll:true});}
 function categoryStep(el,delta){const name=el.closest('[data-category]').dataset.category;categoryMove(name,categoryNames().indexOf(name)+delta);}
 function categoryKey(e){if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();categoryStep(e.currentTarget,['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);}
 function categoryDrag(e){if(e.button!==0||_accessRole!=='admin')return;e.preventDefault();e.stopPropagation();const button=e.currentTarget,card=button.closest('[data-category]'),study=ESTUDIO_ID,name=card.dataset.category,rect=card.getBoundingClientRect(),ghost=card.cloneNode(true),gap=document.createElement('div');ghost.classList.add('shopping-drag-ghost');ghost.style.width=rect.width+'px';ghost.style.height=rect.height+'px';ghost.setAttribute('aria-hidden','true');ghost.querySelectorAll('button,summary').forEach(n=>n.tabIndex=-1);document.body.appendChild(ghost);gap.className='shopping-drop-gap';gap.style.height=rect.height+'px';gap.textContent='Colocar categoría aquí';button.setPointerCapture(e.pointerId);let target=null;card.classList.add('shopping-drag-source');
  const move=ev=>{ghost.style.left=ev.clientX-rect.width/2+'px';ghost.style.top=ev.clientY-24+'px';const hit=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('[data-category]');if(hit&&hit!==card){const box=hit.getBoundingClientRect(),after=ev.clientX>box.left+box.width/2;hit[after?'after':'before'](gap);const names=categoryNames();target=names.indexOf(hit.dataset.category)+(after?1:0);if(names.indexOf(name)<target)target--;}};
  const stop=ev=>{ghost.remove();gap.remove();card.classList.remove('shopping-drag-source');button.removeEventListener('pointermove',move);button.removeEventListener('pointerup',stop);button.removeEventListener('pointercancel',stop);if(ev.type!=='pointercancel'&&study===ESTUDIO_ID&&target!==null)categoryMove(name,target);};button.addEventListener('pointermove',move);button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);move(e);
 }
 function removeLibrary(i){const item=state.library[i],study=ESTUDIO_ID;if(!item)return;askConfirm('¿Eliminar este producto de la biblioteca? Las copias en proyectos se conservan.','Eliminar',()=>{if(study!==ESTUDIO_ID||state.library[i]!==item)return;state.library.splice(i,1);closeModal();render();});}
 function tax(){const panel=document.getElementById('accounting-tax-summary');if(panel)modal('<h3>Resumen fiscal</h3>'+panel.innerHTML+'<button class="btn btn-ghost" onclick="closeModal()">Cerrar</button>');}
 function exportDialog(){const html=vAccounting(),box=document.createElement('div');box.innerHTML=html;const panel=box.querySelector('#accounting-export-source');if(panel)modal('<h3>Periodo y exportación</h3>'+panel.innerHTML+'<button class="btn btn-ghost" onclick="closeModal();render()">Cerrar</button>');}
 function exportPDF(){closeModal();render();exportAccountingPDF();}
 const forecast={view:'lista',month:'',q:'',anchor:iso(new Date())};
 let forecastOwner='';function forecastState(){const key=ESTUDIO_ID+'|'+(state.sessionUser?.id||'');if(key!==forecastOwner){forecastOwner=key;Object.assign(forecast,{view:'lista',month:'',q:'',anchor:iso(new Date())});}return forecast;}
 function forecastRows(rows){const f=forecastState(),q=f.q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return rows.filter(({p,h})=>(!f.month||(h.due||'').startsWith(f.month))&&[h.concept,p.num,p.name,p.client].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));}
 function forecastChange(key,value){const f=forecastState();change(()=>{f[key]=value;if(key==='month'&&value)f.anchor=value+'-01';if(key==='anchor'&&f.month)f.month=value.slice(0,7);});}
 function forecastMove(delta){const f=forecastState(),d=new Date(f.anchor+'T12:00:00');if(f.view==='mes'){d.setDate(1);d.setMonth(d.getMonth()+delta);}else d.setDate(d.getDate()+delta*(f.view==='dia'?1:7));f.anchor=iso(d);if(f.month)f.month=f.anchor.slice(0,7);change(()=>{});}
 function forecastControls(){const f=forecastState();return `<div class="forecast-controls"><label>Buscar pago previsto<input id="forecast-search" type="search" value="${esc(f.q)}" placeholder="Concepto, cliente o proyecto" oninput="WorkflowPolish.forecastSearch(this)"></label><label>Mes<input type="month" value="${esc(f.month)}" onchange="WorkflowPolish.forecastChange('month',this.value)"></label><label>Vista<select onchange="WorkflowPolish.forecastChange('view',this.value)">${[['lista','Lista'],['mes','Mes'],['semana','Semana'],['dia','Día'],['agenda','Agenda']].map(([v,t])=>`<option value="${v}" ${v===f.view?'selected':''}>${t}</option>`).join('')}</select></label></div>`;}
 function forecastCalendar(rows){const f=forecastState(),base=new Date(f.anchor+'T12:00:00'),start=new Date(base);let count=7;
  if(f.view==='mes'){start.setDate(1);start.setDate(start.getDate()-(start.getDay()+6)%7);count=42;}else if(f.view==='semana'){start.setDate(start.getDate()-(start.getDay()+6)%7);}else if(f.view==='dia')count=1;
  const days=Array.from({length:count},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return iso(d);});
  const item=({p,h})=>`<button class="forecast-event" onclick="state.projTab='fin';go('proyecto',${Number(p.id)})"><strong>${esc(h.concept||'Pago previsto')}</strong><span>${esc(p.num)} · ${fmt(h.amount||0)}</span></button>`;
  return `<div class="forecast-navigation"><button class="btn btn-ghost" aria-label="Periodo anterior" onclick="WorkflowPolish.forecastMove(-1)">←</button><strong>${base.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</strong><button class="btn btn-ghost" aria-label="Periodo siguiente" onclick="WorkflowPolish.forecastMove(1)">→</button><button class="btn btn-ghost" onclick="WorkflowPolish.forecastChange('anchor',WorkflowPolish.iso(new Date()))">Hoy</button></div><div class="forecast-calendar-scroll"><div class="forecast-calendar ${['dia','agenda'].includes(f.view)?'forecast-agenda':''}">${!['dia','agenda'].includes(f.view)?['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>'<b>'+d+'</b>').join(''):''}${days.map(day=>`<section class="${day===iso(new Date())?'today':''}"><time>${['dia','agenda'].includes(f.view)?new Date(day+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'}):Number(day.slice(-2))}</time>${rows.filter(r=>r.h.due===day).map(item).join('')}</section>`).join('')}</div></div>${rows.some(r=>!r.h.due)?'<h3>Sin fecha</h3>'+rows.filter(r=>!r.h.due).map(item).join(''):''}`;
 }
 return {eventInfo(date){const events=(state.cal.events||[]).filter(e=>e.date===date);modal('<h3>Actividades del día</h3>'+events.map(e=>'<p>'+esc(e.title)+'</p>').join('')+'<button class="btn btn-ghost" onclick="closeModal()">Cerrar</button>');},get localMotion(){return localMotion;},change,iso,categoryOrder,categoryMove,categoryStep,categoryKey,categoryDrag,removeLibrary,tax,exportDialog,exportPDF,forecastState,forecastRows,forecastControls,forecastCalendar,forecastChange,forecastMove,forecastSearch(el){const f=forecastState(),pos=el.selectionStart;f.q=el.value;render();const next=document.getElementById('forecast-search');next?.focus();try{next?.setSelectionRange(pos,pos);}catch{}},scope(value){if(state.wsMine!==value)change(()=>state.wsMine=value);},contact(value){const order=['Clientes','Proveedores','Contratistas','Arquitectos / Técnicos','Team','Todos'];const dir=order.indexOf(value)>order.indexOf(state.agendaTab||'Clientes')?1:-1;if(state.agendaTab!==value)change(()=>state.agendaTab=value,dir);},calendar(value){change(()=>{state.cal.view=value;state.cal.off=0;});},accountTab(value){if(state.accTab!==value)change(()=>state.accTab=value,value==='out'?1:-1);}};
})();
