import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const part=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
function role(name,dbRole='miembro'){
 const c={_accessRole:null,sb:{},ESTUDIO_ID:'ficticio',state:{myRole:dbRole,users:[{email:'prueba@example.invalid',role:name}]},meMail:()=> 'prueba@example.invalid'};
 vm.createContext(c);vm.runInContext(part('const VIEW_DENY =','function applyRoleNav()'),c);return c;
}
test('existing admin sees finance and administration',()=>{const c=role('Administrador','admin');for(const v of ['contabilidad','facturas','admin'])assert.equal(c.canView(v),true);});
test('existing collaborator navigation denies accounting invoices and admin',()=>{const c=role('Colaborador');assert.equal(c.myAccessLevel(),'colab');for(const v of ['contabilidad','facturas','admin'])assert.equal(c.canView(v),false);assert.equal(c.canView('proyectos'),true);});
test('verified accounting role can read finance but cannot navigate to administration or projects',()=>{const c=role('Gestoría (solo lectura)');c._accessRole='gestoria';assert.equal(c.myAccessLevel(),'gestoria');assert.equal(c.canView('contabilidad'),true);assert.equal(c.canView('facturas'),true);assert.equal(c.canView('admin'),false);assert.equal(c.canView('proyectos'),false);});
test('local admin label cannot override server membership role',()=>{const c=role('Administrador','miembro');assert.equal(c.myAccessLevel(),'miembro');assert.equal(c.canView('facturas'),false);assert.equal(c.canView('admin'),false);});
test('verified collaborator permissions override cached role and finance routes',()=>{const c=role('Administrador','admin');c._accessRole='colaborador';assert.equal(c.myAccessLevel(),'colab');for(const view of ['facturas','presupuestos','prevision','admin'])assert.equal(c.canView(view),false);assert.equal(c.canView('workspace'),true);});
function mail(response){let request;const c={ESTUDIO_ID:'study',_accessRole:'admin',sb:{auth:{getSession:async()=>({data:{session:{access_token:'test-token'}}})}},fetch:async(url,options)=>{request={url,...options};return {ok:response?.ok===true,json:async()=>{if(response instanceof Error)throw response;return response;}};}};vm.createContext(c);vm.runInContext(part('const MAIL_FN=','async function saveUser('),c);return {c,request:()=>request};}
test('mail sends session and study, never trusts client sender or role',async()=>{const f=mail({ok:true});await f.c.mailFnSend({email:'prueba@example.invalid',nombre:'Ficticio',rol:'Administrador',remitente:'spoof'});const r=f.request();assert.equal(r.url,'/api/enviar-invitacion.php');assert.equal(r.headers.Authorization,'Bearer test-token');assert.deepEqual(JSON.parse(r.body),{email:'prueba@example.invalid',estudio_id:'study'});});
test('mail stops without session or administrator role',async()=>{for(const role of ['colaborador','gestoria','cliente',null]){const f=mail({ok:true});f.c._accessRole=role;await assert.rejects(f.c.mailFnSend({email:'x@example.invalid'}));assert.equal(f.request(),undefined);}const f=mail({ok:true});f.c.sb.auth.getSession=async()=>({data:{session:null}});await assert.rejects(f.c.mailFnSend({email:'x@example.invalid'}));assert.equal(f.request(),undefined);});
test('mail stops if study changes while obtaining session',async()=>{const f=mail({ok:true});f.c.sb.auth.getSession=async()=>{f.c.ESTUDIO_ID='other';return {data:{session:{access_token:'test'}}};};await assert.rejects(f.c.mailFnSend({email:'x@example.invalid'}));assert.equal(f.request(),undefined);});
test('mail rejects provider error or invalid JSON',async()=>{for(const response of [{ok:false,error:'rechazado'},null,new SyntaxError('respuesta no JSON')]){const f=mail(response);await assert.rejects(f.c.mailFnSend({email:'prueba@example.invalid'}));}});
