// PostgreSQL isolation and retry tests. In-memory, no network or real users.
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);const db=new PGlite();let checks=0;
const row=async(sql,args=[])=>(await db.query(sql,args)).rows[0];const check=(ok,label)=>{assert.ok(ok,label);checks++;};
const a='11111111-1111-4111-8111-111111111111',b='11111111-1111-4111-8111-111111111112',admin='22222222-2222-4222-8222-222222222221',other='22222222-2222-4222-8222-222222222222',request='33333333-3333-4333-8333-333333333331',request2='33333333-3333-4333-8333-333333333332';
try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create table estudios(id uuid primary key);create table miembros(user_id uuid primary key,estudio_id uuid,rol text);create table datos_estudio(id integer,contenido jsonb);
 insert into estudios values('${a}'),('${b}');insert into miembros values('${admin}','${a}','admin'),('${other}','${b}','admin');insert into datos_estudio values(1,'{"archivos":["conservar"],"importe":345.67}');
 create function public.app_rol_usuario(p_estudio uuid,p_actor uuid) returns text language sql as $$select coalesce((select rol from public.miembros where estudio_id=p_estudio and user_id=p_actor),'sin_acceso')$$;`);
 await db.exec(await fs.readFile(new URL('../SQL/suscripciones-test.sql',import.meta.url),'utf8'));
 const before=(await row('select contenido from datos_estudio')).contenido;
 await db.exec('set role authenticated');await assert.rejects(row('select * from public.billing_test_accounts'));checks++;
 await assert.rejects(row('select billing_test_authorize($1,$2)',[admin,a]));checks++;
 await db.exec('reset role;set role service_role');
 await assert.rejects(row('select billing_test_authorize($1,$2)',[other,a]));checks++;
 const initial=(await row('select billing_test_authorize($1,$2) value',[admin,a])).value;check(initial.status==='not_started','pilot has no invented subscription');
 const first=(await row('select billing_test_begin($1,$2,$3,$4) value',[admin,a,request,'synthetic'])).value;
 const retry=(await row('select billing_test_begin($1,$2,$3,$4) value',[admin,a,request2,'synthetic'])).value;
 check(first.requestId===retry.requestId,'double click reuses persistent request');
 await assert.rejects(row('select billing_test_begin($1,$2,$3,$4)',[admin,a,request2,'different']));checks++;
 await row('select billing_test_checkout_save($1,$2,$3,$4,$5)',[admin,a,request,'cus_fixture','cs_test_fixture']);
 await assert.rejects(row('select billing_test_checkout_save($1,$2,$3,$4,$5)',[admin,a,request,'cus_wrong','cs_test_fixture']));checks++;
 check((await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_wrong',b,request,'cus_fixture','sub_fixture'])).value.ignored,'cross-study webhook ignored');
 const lease=(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_one',a,request,'cus_fixture','sub_fixture'])).value;
 check(!!lease.token,'first event acquires lease');
 check(!(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_two',a,request,'cus_fixture','sub_fixture'])).value.token,'parallel event cannot race fresh fetch');
 const value={customerId:'cus_fixture',subscriptionId:'sub_fixture',status:'active',eligible:true,periodEnd:1999999999};
 await assert.rejects(row('select billing_test_finish($1,$2,$3,$4)', ['evt_one',a,request,value]));checks++;
 await row('select billing_test_finish($1,$2,$3,$4)',['evt_one',a,lease.token,value]);
 check((await row('select billing_test_authorize($1,$2) value',[admin,a])).value.eligible,'verified projection stored');
 check((await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_one',a,request,'cus_fixture','sub_fixture'])).value.duplicate,'duplicate event is a no-op');
 await assert.rejects(row('select billing_test_begin($1,$2,$3,$4)',[admin,a,request2,'synthetic']));checks++;
 const lease2=(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_cancel',a,request,'cus_fixture','sub_fixture'])).value;
 await row('select billing_test_finish($1,$2,$3,$4)',['evt_cancel',a,lease2.token,{...value,status:'canceled',eligible:false}]);
 check(!(await row('select billing_test_authorize($1,$2) value',[admin,a])).value.eligible,'cancellation updates only test projection');
 await row('select billing_test_begin($1,$2,$3,$4)',[admin,a,request2,'synthetic']);
 await row('select billing_test_checkout_save($1,$2,$3,$4,$5)',[admin,a,request2,'cus_fixture','cs_test_second']);
 const oldLease=(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_old_pending',a,request,'cus_fixture','sub_fixture'])).value;
 await row('select billing_test_finish($1,$2,$3,$4)',['evt_old_pending',a,oldLease.token,{...value,status:'canceled',eligible:false}]);
 check((await row('select billing_test_begin($1,$2,$3,$4) value',[admin,a,request2,'synthetic'])).value.requestId===request2,'old event preserves a new pending checkout');
 const lease3=(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_new',a,request2,'cus_fixture','sub_second'])).value;
 await row('select billing_test_finish($1,$2,$3,$4)',['evt_new',a,lease3.token,{...value,subscriptionId:'sub_second'}]);
 check((await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_old',a,request,'cus_fixture','sub_fixture'])).value.ignored,'superseded subscription cannot overwrite new one');
 const expired=(await row('select billing_test_claim($1,$2,$3,$4,$5) value',['evt_expiry',a,request2,'cus_fixture','sub_second'])).value;
 await db.exec(`reset role;update billing_test_accounts set sync_until=now()-interval '1 second';set role service_role;`);
 await assert.rejects(row('select billing_test_finish($1,$2,$3,$4)',['evt_expiry',a,expired.token,{...value,subscriptionId:'sub_second'}]));checks++;
 await db.exec('reset role');check(JSON.stringify((await row('select contenido from datos_estudio')).contenido)===JSON.stringify(before),'all existing documents preserved');
 check((await row('select count(*) n from miembros')).n===2,'pilot memberships preserved');
 console.log(`${checks} billing PostgreSQL checks passed; no network.`);
}finally{await db.close();}
