import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import Catalog from '../app/catalog-core.js';
const source=fs.readFileSync(new URL('../app/catalog-ui.js',import.meta.url),'utf8');
function context(){
 const item={id:8,name:'Partida',price:40,unit:'ud',tipo:'Partida',cat:'Obra'},inputs={};
 const ctx={state:{catalog:[item],draft:{kind:'presupuesto',lines:[Catalog.line(item)]},_catSel:{8:1}},ESTUDIO_ID:'a',_accessRole:'admin',ModernoCatalog:Catalog,ModernoDaily:{escape:s=>s},fmt:String,unitLabel:String,byBrand:x=>x,ico:()=>'',catPickCount(){},persistNow(){},cloudDirty(){},render(){},closeModal(){},modal(html){ctx.html=html;},toast(m){ctx.messages.push(m);},messages:[],askConfirm(a,b,fn){ctx.confirm=fn;},document:{getElementById(id){return inputs[id]??= {value:''};}},inputs};
 vm.createContext(ctx);vm.runInContext(source+';globalThis.ui=CatalogUI;',ctx);return ctx;
}
function fields(c){for(const [k,v] of Object.entries({leN:'Partida',leP:'60',leQ:'1',leK:'',leD:'',leC:'Obra',leU:'ud',leV:''}))c.inputs[k]={value:v};}
test('price choice waits for explicit selection and never mutates catalog',()=>{const c=context();fields(c);c.ui.saveLine(0);assert.equal(c.state.draft.lines[0].price,40);assert.equal(c.state.catalog[0].price,40);c.inputs.catPriceStudy.onclick();assert.equal(c.state.draft.lines[0].price,60);assert.ok(c.state.draft.lines[0].catalogPriceIntent);assert.equal(c.state.catalog[0].price,40);});
test('only document and cancelled choice cannot update catalog',()=>{const c=context();fields(c);c.ui.saveLine(0);assert.equal(c.state.draft.lines[0].price,40);c.inputs.catPriceOnly.onclick();assert.equal(c.state.draft.lines[0].price,60);assert.equal(c.state.draft.lines[0].catalogPriceIntent,undefined);assert.equal(c.state.catalog[0].price,40);});
test('price dialog refuses changed study or draft',()=>{for(const change of [c=>c.ESTUDIO_ID='b',c=>c.state.draft={lines:[]}]){const c=context();fields(c);const original=c.state.draft;c.ui.saveLine(0);change(c);c.inputs.catPriceStudy.onclick();assert.equal(original.lines[0].price,40);assert.ok(c.messages.length);}});
test('collaborator and issued invoice do not offer catalog update',()=>{for(const change of [c=>c._accessRole='colaborador',c=>Object.assign(c.state.draft,{kind:'factura',editRef:'FC-1'})]){const c=context();fields(c);change(c);c.ui.saveLine(0);assert.equal(c.state.draft.lines[0].price,60);assert.equal(c.state.draft.lines[0].catalogPriceIntent,undefined);assert.equal(c.inputs.catPriceStudy,undefined);}});
test('delete archives historical source but rejects changed study or item',()=>{const c=context();c.ui.remove(8);c.confirm();assert.equal(Catalog.search(c.state.catalog).length,0);assert.equal(c.state.catalogArchive[0].price,40);assert.equal(c.state.catalog[0].id,8);for(const change of [c=>c.ESTUDIO_ID='b',c=>c.state.catalog[0].price=99]){const c=context();c.ui.remove(8);change(c);c.confirm();assert.equal(c.state.catalog[0].archived,undefined);}});
test('picker refuses stale prices and changed draft instead of copying unseen values',()=>{for(const change of [c=>c.state.catalog[0].price=99,c=>c.ESTUDIO_ID='b',c=>c.state.draft={lines:[]}]){const c=context();c.ui.openPicker();change(c);const count=c.state.draft.lines.length;c.ui.add();assert.equal(c.state.draft.lines.length,count);assert.ok(c.messages.length);}});
test('picker copies selected items with explicit snapshots',()=>{const c=context();c.ui.openPicker();c.ui.add();assert.equal(c.state.draft.lines.length,2);assert.equal(c.state.draft.lines[1].catalogSource.id,8);assert.equal(c.state.draft.lines[1].price,40);});
