import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const c=vm.createContext({});vm.runInContext(fs.readFileSync(new URL('../app/client-portal-site.js',import.meta.url),'utf8')+';globalThis.portal=ClientPortalSite;',c);
test('client task board projects only title state date, never internal notes or files',()=>{const p={tasks:[{title:'Medidas',col:'rev',due:'2026-09-25',notes:'PRIVADO',cost:50,files:['secreto']},{title:'Plano',col:'listo'}],obraF:[{items:[{t:'No es una tarea CRM',done:true}]}]};const rows=c.portal.tasks(p,{});assert.equal(rows.length,2);assert.equal(rows[0].col,'rev');assert.equal(rows[0].due,'2026-09-25');assert.equal(rows[1].done,true);assert.deepEqual(Object.keys(rows[0]),['title','col','due','done']);const html=c.portal.taskHTML(rows);assert.match(html,/25\/09\/2026/);assert.match(html,/En revisiÃ³n/);assert.doesNotMatch(html,/PRIVADO|secreto|No es una tarea/);});
test('task titles escaped and missing dates explicit',()=>{const html=c.portal.taskHTML(c.portal.tasks({tasks:[{title:'<img onerror=evil>',col:'pend'}]}));assert.match(html,/&lt;img/);assert.match(html,/Sin fecha prevista/);assert.doesNotMatch(html,/<img/);});

test('shopping shows unit prices, correct quantities and totals, excludes hidden lists',()=>{c.cliModeOf=r=>r.cliMode;c.fmt=n=>n+' EUR';c.fileImageAttrs=()=>'';const html=c.portal.shoppingHTML({id:1,rooms:[{id:2,name:'Salón',cliMode:'ver',sections:[{items:[{name:'Lámpara',price:89,qty:2,unit:'ud',img:'image.jpg'},{name:'Sin unidades',price:50,qty:0}]}]},{name:'Oculta',cliMode:'off',sections:[{items:[{name:'Privado',price:999}]}]}]});assert.match(html,/89 EUR <small>\/ ud/);assert.match(html,/178 EUR/);assert.match(html,/Resumen de compras/);assert.match(html,/Ampliar imagen de Lámpara/);assert.doesNotMatch(html,/999|Privado|Oculta/);});
test('calendar initially opens first planned month even when it is not the current month',()=>{const p={obraF:[{start:'2027-02-10',end:'2027-02-12'},{start:'2026-11-08',end:'2026-11-15'}]};const d=c.portal.calendarBase(p,new Date(2026,8,21));assert.equal(d.getMonth(),10);assert.equal(d.getFullYear(),2026);assert.equal(c.portal.calendarBase(p,new Date(),1).getMonth(),11);});
test('cover only uses an explicitly selected shared image',()=>{const privateFile={docKind:'portal-cover',type:'image/png',data:'hidden',cli:false};const normalFile={type:'image/png',data:'normal'};assert.equal(c.portal.cover({files:[privateFile,normalFile]}),undefined);const chosen={docKind:'portal-cover',type:'image/png',data:'cover',cli:true};assert.equal(c.portal.cover({files:[privateFile,chosen]}),chosen);});

test('uploading a cover retains prior files and persists the selected shared image',async()=>{const old={name:'Anterior',docKind:'portal-cover',type:'image/png',data:'old',cli:true};c.state={projects:[{id:1,files:[old]}]};c.fileViewIdentity=()=> 'study';c.toast=()=>{};c.fileUp=async()=> 'storage://archivos/study/new';c.hoyEs=()=> '21/09/2026';let saves=0;c.persistSoon=()=>{saves++};c.window={render:()=>{}};await c.portal.uploadCover(1,{name:'Portada.png',type:'image/png',size:300});assert.equal(c.state.projects[0].files.length,2);assert.equal(old.docKind,undefined);assert.equal(c.portal.cover(c.state.projects[0]).data,'storage://archivos/study/new');assert.equal(saves,1);c.portal.removeCover(1);assert.equal(c.portal.cover(c.state.projects[0]),undefined);assert.equal(c.state.projects[0].files.length,2);});
