import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const code=html.slice(html.indexOf('async function cloudConnectionStep('),html.indexOf('function _dataUrlBlob('));
function fixture(rpc){const c={_accessConnecting:false,_accessAttempt:0,_accessLoading:true,_accessError:'',ESTUDIO_ID:null,LS_KEY:'test',state:{},console:{warn(){}},setTimeout,clearTimeout,syncTag(){},render(){},localStorage:{getItem(){return null},setItem(){}},cloudKeepPendingCopy(){},sb:{rpc}};vm.createContext(c);vm.runInContext(code,c);return c;}
test('join failure leaves explicit error with retry available and no cached content authorized',async()=>{const c=fixture(async()=>({error:{message:'offline'}}));await c.cloudLoad();assert.match(c._accessError,/No se pudo comprobar/);assert.equal(c._accessConnecting,false);assert.equal(c._accessLoading,true);});
test('permission rejection is explained, without unlocking cached data',async()=>{const c=fixture(async name=>name==='unirse_al_estudio'?{data:{estudio_id:'fake',rol:'miembro'}}:{data:'sin_acceso'});await c.cloudLoad();assert.match(c._accessError,/permisos/);assert.equal(c._accessLoading,true);assert.equal(c._accessConnecting,false);});
test('a hung connection times out and frees its timer',async()=>{const c=fixture();let timeout,cleared=false;c.setTimeout=fn=>{timeout=fn;return 1};c.clearTimeout=()=>{cleared=true};c._accessAttempt=1;const p=c.cloudConnectionStep(new Promise(()=>{}),1);timeout();await assert.rejects(p,/tarda demasiado/);assert.equal(cleared,true);});
test('overlapping entry attempts issue only one join call',async()=>{let resolve,calls=0;const c=fixture(()=>{calls++;return new Promise(r=>resolve=r)});const first=c.cloudLoad();await c.cloudLoad();assert.equal(calls,1);resolve({error:{message:'offline'}});await first;assert.equal(c._accessConnecting,false);});
test('response from a previous session cannot proceed',async()=>{const c=fixture();c._accessAttempt=2;await assert.rejects(c.cloudConnectionStep(Promise.resolve({data:'old'}),1),/sesión ha cambiado/);});
