import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const src=fs.readFileSync(new URL('../app/document-builder.js',import.meta.url),'utf8');
function setup(){const storage=new Map(),messages=[],c={ESTUDIO_ID:'study',_accessRole:'admin',state:{sessionUser:{id:'u'},brandFilter:'all',account:{},emitter:{name:'Estudio',nif:'E'},docs:[],projects:[{id:1,num:'PR-1',name:'Vivienda',brand:'cm',client:'Ana',files:[]}],clients:[{name:'Ana',nif:'C',addr:'Calle',email:'a@example.test'}]},wsOrder:['cm'],crypto:{randomUUID:()=>String(Math.random())},localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)},toast:x=>messages.push(x),persistSoon(){},render(){},modal(){},mb:{classList:{add(){}}},Date,console};vm.createContext(c);vm.runInContext(src+';this.api=ModernoDocuments;this.draft=()=>dg;',c);return {c,storage,messages}}
test('generator imports project and unique client as a snapshot without changing contacts',()=>{const {c}=setup();c.dgOpen(0);c.dgProject('1');assert.equal(c.draft().values.cliente_nif,'C');assert.equal(c.draft().projectId,1);c.dgSet('cliente','Changed');assert.equal(c.state.clients[0].name,'Ana');});
test('ambiguous client names never automatically select fiscal data',()=>{const {c}=setup();c.state.clients.push({name:'Ana',nif:'Other'});c.dgOpen(0);c.dgProject('1');assert.equal(c.draft().values.cliente_nif,'');});
test('preview escapes HTML and keeps unresolved fields detectable',()=>{const {c}=setup();c.dgOpen(0);c.dgSet('cliente','<img onerror=x>');assert.doesNotMatch(c.api.paper(c.draft()),/<img/);assert.ok(c.api.missing(c.draft()).length);assert.equal(c.dgReady(),false);});
test('excluded clauses are not printed and ordering changes the output',()=>{const {c}=setup();c.dgOpen(0);const old=c.draft().sections[0].title;c.dgMove(0,1);assert.equal(c.draft().sections[1].title,old);c.dgClause(1,'enabled',false);assert.ok(!c.api.paper(c.draft()).includes(old));});
test('saving creates editable record without replacing legacy documents',()=>{const {c}=setup();c.state.docs.push({name:'Legacy',body:'keep'});c.dgOpen(0);c.dgSave(false);assert.equal(c.state.docs.length,2);assert.equal(c.state.docs[0].body,'keep');c.dgSet('title','New');c.dgSave(false);assert.equal(c.state.docs.length,2);assert.equal(c.state.docs[1].name,'New');});
test('concurrent document changes are not overwritten',()=>{const {c,messages}=setup();c.dgOpen(0);c.dgSave(false);c.state.docs[0].name='Remote';c.dgSet('title','Local');c.dgSave(false);assert.equal(c.state.docs[0].name,'Remote');assert.match(messages.at(-1),/otra sesión/);});
test('template strips selected client and project fields and opens as a new document',()=>{const {c}=setup();c.dgOpen(0);c.dgProject('1');c.dgSave(true);assert.equal(c.state.docs[0].generator.values.cliente,'');assert.equal(c.state.docs[0].generator.projectId,'');c.dgLoad(0);assert.equal(c.draft().id,null);assert.ok(c.draft().values.fecha);});
test('draft recovery is scoped to identity and writing is denied after study change',()=>{const {c}=setup();c.dgOpen(0);c.dgSet('title','Recover me');c.dgResume();assert.equal(c.draft().title,'Recover me');c.ESTUDIO_ID='other';c.dgSave(false);assert.equal(c.state.docs.length,0);});
test('collaborator cannot open or save generator documents',()=>{const {c}=setup();c._accessRole='colaborador';assert.equal(c.dgHome(),'');c.dgOpen(0);assert.equal(c.draft(),null);});
test('completed copy is attached privately and does not overwrite existing files',()=>{const {c}=setup();c.dgOpen(7);c.dgProject('1');c.dgAdd('');c.dgClause(0,'text','Contenido acordado.');c.state.projects[0].files.push({name:'existing'});assert.ok(c.dgReady());c.dgAttach();assert.equal(c.state.projects[0].files.length,2);assert.equal(c.state.projects[0].files[1].cli,false);assert.match(c.state.projects[0].files[1].body,/Contenido acordado/);});
