import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const helpers=html.slice(html.indexOf('function folderPhotoSources('),html.indexOf('function folderCard('));
const sample='data:image/jpeg;base64,YQ==';
function context(extra={}){const c={...extra};vm.createContext(c);vm.runInContext(helpers,c);return c;}
test('folder photos accept only bounded embedded thumbnails, not external URLs or HTML',()=>{const c=context();assert.equal(c.folderPhotoSources({folderPhotos:[sample,'https://example.invalid/p.jpg','data:image/svg+xml;base64,YQ==',sample+'" onerror="x',sample+'a'.repeat(48000)]}).length,1);assert.equal(c.folderPhotoSources({}).length,0);assert.equal(c.folderPhotoSources({folderPhotos:Array(5).fill(sample)}).length,3);});
test('customizing thumbnails preserves original project attachments',()=>{const project={id:1,name:'Demo',files:[{data:'storage://archivos/test/original.jpg'}]};const original=JSON.stringify(project.files);const c=context({state:{projects:[project]},cz:{folderPhotos:[sample],name:'Demo',color:null,icon:'',tags:'',client:''},closeModal(){},render(){},toast(){}});vm.runInContext(html.slice(html.indexOf('function saveCustomize('),html.indexOf('function deleteProject(')),c);c.saveCustomize(1);assert.equal(project.folderPhotos[0],sample);assert.equal(JSON.stringify(project.files),original);c.cz.folderPhotos=[];c.saveCustomize(1);assert.equal(project.folderPhotos.length,0);assert.equal(JSON.stringify(project.files),original);});
test('save waits for thumbnail preparation',()=>{const project={id:1,name:'Demo'};const c=context({state:{projects:[project]},cz:{busy:true}});vm.runInContext(html.slice(html.indexOf('function saveCustomize('),html.indexOf('function deleteProject(')),c);c.saveCustomize(1);assert.deepEqual(project,{id:1,name:'Demo'});});
test('cancelled image preparation cannot change the project or a later dialog',async()=>{let resolve;const input={isConnected:true},status={};const draft={folderPhotos:[],busy:false};const c=context({cz:draft,document:{getElementById:id=>id==='czPhotosInput'?input:status},czPhotosDraw(){},czPreviewDraw(){throw Error('closed preview updated');},folderPhotoThumbnail:()=>new Promise(r=>resolve=r)});vm.runInContext(html.slice(html.indexOf('async function czAddPhotos('),html.indexOf('function saveCustomize(')),c);const pending=c.czAddPhotos([{}]);input.isConnected=false;resolve(sample);await pending;assert.equal(draft.folderPhotos.length,0);});
test('chosen folder colors override beige and choose readable text',()=>{const code=html.slice(html.indexOf('function folderColors('),html.indexOf('const state ='));const c={PALETTE:{},darken:()=> '#333333'};vm.createContext(c);vm.runInContext(code,c);assert.equal(c.folderColors({}).front,'#f5f2ec');assert.equal(c.folderColors({color:'#000000'}).ink,'#ffffff');assert.equal(c.folderColors({color:'#D3DDC8'}).front,'#D3DDC8');assert.equal(c.folderColors({color:'#ffffff'}).ink,'#242424');assert.equal(c.folderColors({color:'#bad'}).front,'#f5f2ec');});
