import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import daily from '../app/daily-work.js';
const code=fs.readFileSync(new URL('../app/gestoria.js',import.meta.url),'utf8');
function fixture(){let request;const c={_accessRole:'gestoria',_gestoriaData:{entries:[{date:'09/09/2026',concept:'<Gasto>',amount:12,file:{name:'justificante.pdf',type:'application/pdf',data:'storage://archivos/ficticio/a.pdf'}}],invoices:[],projects:[]},ModernoDaily:daily,fmt:x=>String(x),ESTUDIO_ID:'ficticio',sb:{rpc:async(n,p)=>{request={n,p};return {data:{readonly:true,entries:[],invoices:[],projects:[]}};}},showLogin(){},render(){},syncTag(){},document:{getElementById(){return null;},createElement(){return {click(){c.clicked=true;}};}}};vm.createContext(c);vm.runInContext(code,c);return {c,request:()=>request};}
test('accounting screen only offers refresh PDF and summary actions',()=>{const {c}=fixture();const output=c.vGestoria();assert.match(output,/Solo lectura/);assert.match(output,/&lt;Gasto&gt;/);assert.ok(!/<input|<select|<textarea|onclick="(?:save|del|edit|new)/i.test(output));});
test('files available to accounting exclude non-PDF and empty references',()=>{const {c}=fixture();const files=c.gestoriaFiles({files:[{name:'a.pdf',url:'https://example.invalid/a.pdf'},{name:'b.png',type:'image/png',url:'https://example.invalid/b.png'},{name:'c.pdf'}]});assert.equal(files.length,1);});
test('refresh uses read-only RPC and replaces old displayed data',async()=>{const f=fixture();await f.c.gestoriaLoad();assert.equal(f.request().n,'gestoria_consultar');assert.equal(f.request().p.p_estudio,'ficticio');assert.equal(f.c._gestoriaData.entries.length,0);});
test('failed refresh clears the display rather than retaining previously authorized data',async()=>{const {c}=fixture();c.sb.rpc=async()=>({error:{message:'denied'}});await c.gestoriaLoad();assert.equal(c._gestoriaData,null);});
test('download never opens when signing is refused',async()=>{const {c}=fixture();c.fileResolveForView=async()=>false;await c.gestoriaPdf(0,0);assert.equal(c.clicked,undefined);});
test('invoice attachments offer the original separately from the consultation summary',()=>{const {c}=fixture();c._gestoriaData.invoices=[{file:{name:'original.pdf',data:'storage://archivos/ficticio/original.pdf'}}];const html=c.vGestoria();assert.match(html,/gestoriaPdf\(0,0,&quot;invoices&quot;\)/);assert.match(html,/original.pdf/);assert.match(html,/Resumen PDF/);});
test('a download finishing after logout must not open a document',async()=>{const {c}=fixture();c.fileResolveForView=async()=>{c._accessRole=null;return 'https://example.invalid/signed.pdf';};await c.gestoriaPdf(0,0);assert.equal(c.clicked,undefined);});
test('a response for a previous study must not replace the current consultation',async()=>{const {c}=fixture();const original=c._gestoriaData;c.sb.rpc=async()=>{c.ESTUDIO_ID='otro';return {data:{readonly:true,entries:[]}};};await c.gestoriaLoad();assert.equal(c._gestoriaData,original);});
