import test from 'node:test';import assert from 'node:assert/strict';
import {PLANS,approvedPrice} from '../supabase/functions/billing/plans.mjs';
import {generatePDF} from '../supabase/functions/billing/pdf-job.mjs';
test('approved plan terms distinguish unlimited from undecided',()=>{assert.equal(PLANS.free.capturesPerMonth,25);assert.equal(PLANS.free.pdfsPerMonth,10);assert.equal(PLANS.pro.unitAmount,2200);assert.equal(PLANS.team.unitAmount,3800);assert.equal(PLANS.team.perAdditionalInternalUser,true);assert.equal(PLANS.pro.capturesPending,true);assert.equal(PLANS.pro.pdfsUnlimited,true);assert.equal(PLANS.free.personalLibrary,null);});
test('Stripe prices must be monthly EUR inclusive at approved amount',()=>{
 const p={livemode:false,active:true,type:'recurring',unit_amount:2200,currency:'eur',tax_behavior:'inclusive',recurring:{interval:'month',interval_count:1}};
 assert.equal(approvedPrice('pro',p),true);for(const changes of [{tax_behavior:'exclusive'},{unit_amount:2201},{currency:'usd'},{livemode:true}])assert.equal(approvedPrice('pro',{...p,...changes}),false);
 assert.equal(approvedPrice('team',{...p,unit_amount:3800}),true);assert.equal(approvedPrice('free',p),false);
});
function pdfFixture(overrides={}){const calls=[];return {calls,deps:{readAuthorizedSnapshot:async()=>({key:'doc',revision:'server-revision',snapshot:{title:'Server data'}}),reserve:async()=>({id:'receipt',modernoBrand:true}),render:async(s,options)=>{calls.push(['render',s,options]);return new TextEncoder().encode('%PDF-1.7\nsynthetic fixture\n%%EOF');},put:async()=>calls.push(['put']),finish:async()=>calls.push(['finish']),fail:async()=>calls.push(['fail']),sign:async()=> 'signed-test-url',...overrides}};}
test('PDF consumes only after generated bytes are stored, branding comes from server',async()=>{
 const f=pdfFixture();await generatePDF({actor:'a',study:'s',document:'id'},f.deps);assert.deepEqual(f.calls.map(x=>x[0]),['render','put','finish']);assert.equal(f.calls[0][2].modernoBrand,true);
});
test('PDF errors do not consume; same revision redownload skips rendering',async()=>{
 const f=pdfFixture({render:async()=>new Uint8Array([1,2,3])});await assert.rejects(generatePDF({actor:'a',study:'s',document:'id'},f.deps));assert.deepEqual(f.calls,[['fail']]);
 const cached=pdfFixture({reserve:async()=>({cached:true,path:'existing'})});assert.equal((await generatePDF({actor:'a',study:'s',document:'id'},cached.deps)).cached,true);assert.equal(cached.calls.length,0);
});
