import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {webcrypto} from 'node:crypto';import spec from '../app/specifications.js';
const source=fs.readFileSync(new URL('../app/product-operations.js',import.meta.url),'utf8');
function fixture(impl,role='admin'){
 const calls=[],messages=[],box={innerHTML:''},fields={opsBody:box,opsPortal:box,opsNote:{value:'Aprobación por escrito ficticia'}};
 const p={id:1,num:'P-1',name:'Proyecto',rooms:[]};const c={crypto:webcrypto,ModernoSpec:spec,ModernoDaily:{escape:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')},fmt:v=>v+' EUR',state:{projects:[p],portalAnon:'ficticio'},ESTUDIO_ID:'estudio',_accessRole:role,_cloudBusy:false,_saveErr:false,_cloudHash:{proyectos:JSON.stringify([p])},CLOUD_BLOCKS:{proyectos:{get:()=>[p]}},canon:JSON.stringify,specPrepare:()=>{},persistNow(){},cloudFlush:async()=>{},document:{getElementById:id=>fields[id],querySelectorAll:()=>[]},toast:v=>messages.push(v),modal(){},sb:{rpc:async(name,args)=>{calls.push({name,args});return impl(name,args,calls);}}};vm.createContext(c);vm.runInContext(source,c);return {api:c.ProductOps,c,calls,messages,box,fields};
}
const approval={id:'11111111-1111-4111-8111-111111111111',estado:'pendiente',version:1,vigente:true,snapshot:{id:'silla',name:'Silla',qty:1,price:100},revision:'revision-a'};
test('portal only confirms after a successful response and reuses the attempt on uncertain failure',async()=>{let fail=true;const f=fixture(async(name)=>{if(name==='portal_aprobaciones')return {data:[approval]};if(fail)return {error:{message:'Sin conexión'}};return {data:{registrado:true}};});await f.api.portal();await f.api.decide(0,'aprobada');assert.ok(!f.messages.includes('Respuesta registrada'));fail=false;await f.api.decide(0,'aprobada');const writes=f.calls.filter(x=>x.name==='portal_aprobacion_decidir');assert.equal(writes.length,2);assert.equal(writes[0].args.p_operacion,writes[1].args.p_operacion);assert.equal(writes[1].args.p_revision,'revision-a');assert.ok(f.messages.includes('Respuesta registrada'));});
test('double click while a portal decision is running cannot send two decisions',async()=>{let release;const f=fixture(async(name)=>name==='portal_aprobaciones'?{data:[approval]}:new Promise(r=>release=r));await f.api.portal();const pending=f.api.decide(0,'aprobada');await f.api.decide(0,'aprobada');assert.equal(f.calls.filter(x=>x.name==='portal_aprobacion_decidir').length,1);release({data:{registrado:true}});await pending;});
test('staff operations stop when project changes are not saved',async()=>{const r={...approval,tipo:'aprobacion',creado:'2026-09-11',contenido:{snapshot:approval.snapshot}};const f=fixture(async()=>({data:[r]}));await f.api.open(1);f.c._cloudHash.proyectos='old';await f.api.noteSave(r.id,'aprobacion_manual');assert.equal(f.calls.filter(x=>x.name==='app_operaciones_accion').length,0);assert.ok(f.messages.some(m=>m.includes('pendientes')));});
test('collaborator cannot open commercial operations from the client',async()=>{const f=fixture(async()=>{throw Error('must not call')},'colaborador');await f.api.open(1);assert.equal(f.calls.length,0);});
test('staff write retries reuse their operation identifier',async()=>{const r={...approval,tipo:'aprobacion',creado:'2026-09-11',contenido:{snapshot:approval.snapshot}};let fail=true;const f=fixture(async(name)=>name==='app_operaciones_lee'?{data:[r]}:fail?{error:{message:'Red interrumpida'}}:{data:r});await f.api.open(1);await f.api.noteSave(r.id,'aprobacion_manual');fail=false;await f.api.noteSave(r.id,'aprobacion_manual');const writes=f.calls.filter(x=>x.name==='app_operaciones_accion');assert.equal(writes.length,2);assert.equal(writes[0].args.p_operacion,writes[1].args.p_operacion);});
test('request PDF escapes text and never includes sale price, internal cost or margin',()=>{const f=fixture(async()=>({data:[]}));const r={id:'12345678',tipo:'solicitud',estado:'preparada',contenido:{proveedor:'<img src=x>',lineas:[{qty:2,snapshot:{name:'<script>bad</script>',price:9999,cost:8888,margin:47,unit:'ud'}}]}};const html=f.api.printMarkup(r,{num:'P',name:'Demo'});assert.match(html,/&lt;script>/);assert.doesNotMatch(html,/<script>|9999|8888|47/);});
test('order PDF uses only agreed purchase values and labels tax scope and drafts',()=>{const f=fixture(async()=>({data:[]}));const r={id:'12345678',tipo:'pedido',estado:'borrador',contenido:{proveedor:'Demo',total:120,lineas:[{qty:2,precio:60,snapshot:{name:'Silla',price:9000,cost:8000,unit:'ud'}}]}};const html=f.api.printMarkup(r,{num:'P',name:'Demo'});assert.match(html,/BORRADOR/);assert.match(html,/Total sin impuestos: 120 EUR/);assert.doesNotMatch(html,/9000|8000/);});
test('section identity survives repeat preparation without changing article fields',()=>{const p={rooms:[{id:1,sections:[{name:'A',items:[{name:'Silla',qty:1,price:100,files:['original.pdf']}]},{name:'B',items:[]}]}]};spec.prepare(p);const ids=p.rooms[0].sections.map(x=>x.id),saved=JSON.stringify(p);assert.equal(new Set(ids).size,2);spec.prepare(p);assert.equal(JSON.stringify(p),saved);assert.deepEqual(p.rooms[0].sections[0].items[0].files,['original.pdf']);});
test('new order PDF prints server tax totals without altering legacy total',()=>{const f=fixture(async()=>({data:[]}));const r={id:'12345678',tipo:'pedido',estado:'confirmado',contenido:{proveedor:'Demo',total:120,economia:{base:130,impuestos:26.2,retencion:6.5,transporte:10,total:149.7},lineas:[{qty:2,precio:60,snapshot:{name:'Silla',price:9000}}]}};const html=f.api.printMarkup(r,{num:'P',name:'Demo'});assert.match(html,/Total del pedido: 149.7 EUR/);assert.match(html,/Impuestos: 26.2 EUR/);assert.match(html,/Retención: 6.5 EUR/);assert.doesNotMatch(html,/9000/);assert.equal(r.contenido.total,120);});
test('saved financial response survives a subsequent list refresh failure',async()=>{const r={id:'11111111-1111-4111-8111-111111111111',tipo:'pedido',estado:'confirmado',version:2,creado:'2026-09-11',contenido:{proveedor:'Demo',lineas:[]}};let reads=0;const f=fixture(async(name)=>name==='app_operaciones_lee'?(++reads===1?{data:[r]}:{error:{message:'Sin conexión'}}):{data:{...r,version:3}});await f.api.open(1);const saved=await f.api.money('pago',{id:r.id,version:2,importe:1});assert.equal(saved.version,3);assert.equal(f.api.getRecord(r.id).version,3);assert.ok(f.messages.some(x=>x.includes('Registro guardado')));});
