import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../app/project-quotes.js',import.meta.url),'utf8'),c);const Q=c.ProjectQuotes;
const row=()=>({room:{id:1,name:'Sala'},item:{id:'silla',name:'Silla',qty:2,price:100,cost:60,unit:'ud',material:'Roble',note:'Privada',files:[{url:'privada'}]}});
test('invalid costs cannot silently turn into null during serialization',()=>{for(const cost of ['err',Infinity,-1]){const r=row();r.item.cost=cost;assert.throws(()=>Q.line(r,'s',1));}});
test('document snapshot preserves identity and price after project edits',()=>{const r=row(),l=Q.line(r,'study',5);r.item.price=900;r.item.material='Metal';assert.equal(l.price,100);assert.equal(l.source.snapshot.material,'Roble');assert.equal(l.source.item,'silla');assert.equal(l.source.snapshot.cost,undefined);assert.equal(l.source.snapshot.files,undefined);assert.equal(l.source.snapshot.note,undefined);});
test('same names in another project or study cannot create document links',()=>{const l=Q.line(row(),'study',5),qs=[{ref:'P-1',status:'acc',lines:[l]}];assert.equal(Q.references(qs,'study',5,'silla').length,1);assert.equal(Q.references(qs,'foreign',5,'silla').length,0);assert.equal(Q.references(qs,'study',6,'silla').length,0);assert.equal(Q.references(qs,'study',5,'other').length,0);});
test('missing values reject rather than invent quantities or prices',()=>{for(const [field,value] of [['qty',null],['qty',0],['price',''],['price',Infinity]]){const r=row();r.item[field]=value;assert.throws(()=>Q.line(r,'s',1));}const r=row();r.item.cost=null;r.item.price=0;assert.equal(Q.line(r,'s',1).cost,null);assert.equal(Q.line(r,'s',1).price,0);});
test('project reassignment does not silently attach source lines elsewhere',()=>{const l=Q.line(row(),'s',5);assert.throws(()=>Q.validate({projectId:6,lines:[l]},'s'));assert.throws(()=>Q.validate({projectId:5,lines:[l]},'other'));Q.validate({projectId:5,lines:[l]},'s');Q.validate({projectId:6,lines:[{name:'Historic line'}]},'s');});
test('document references survive serialization and do not mutate historical documents',()=>{const qs=[{ref:'P-1',lines:[Q.line(row(),'s',5)]},{ref:'P-old',lines:[{name:'Silla',price:80}]}],before=JSON.stringify(qs);const refs=Q.references(JSON.parse(before),'s',5,'silla');refs[0].snapshot.price=9;assert.equal(JSON.stringify(qs),before);assert.equal(refs.length,1);});
