import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../app/purchase-finance.js',import.meta.url),'utf8');
function fixture(){const writes=[],messages=[],box={innerHTML:''};const fields={opsBody:box,pmNote:{value:'Prueba ficticia'},pmAmount:{value:'50'},pmDate:{value:'2026-09-11'},pmTax0:{value:''},pmTransport:{value:'0'},pmTransportTax:{value:'0'},pmRetention:{value:'0'},pmInvoice:{value:''}};
 const order={id:'11111111-1111-4111-8111-111111111111',version:3,proyecto_id:'1',estado:'confirmado',contenido:{proveedor:'<Proveedor>',lineas:[{snapshot:{name:'Silla'},qty:2,precio:60,recibido:1}],saldos:{total:145.2,pagado:0,reintegrado:0,abonado:0,pendiente:145.2,a_recuperar:0}}};
 const c={Date,ModernoDaily:{escape:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')},fmt:v=>v+' EUR',document:{getElementById:id=>fields[id]},state:{entries:[{id:1,kind:'out',pid:1,concept:'Factura',amount:145.2},{id:2,kind:'in',pid:1,concept:'Venta',amount:100},{id:3,kind:'out',pid:99,concept:'Ajena',amount:500}],entriesDel:{}},toast:v=>messages.push(v),ProductOps:{getRecord:()=>order,money:async(kind,data)=>{writes.push({kind,data});return null;}}};vm.createContext(c);vm.runInContext(source,c);c.PurchaseFinance.open(order.id);return {api:c.PurchaseFinance,fields,order,writes,messages,box};}
test('unknown tax cannot silently become zero',async()=>{const f=fixture();await f.api.saveConditions();assert.equal(f.writes.length,0);f.fields.pmTax0.value='0';await f.api.saveConditions();assert.equal(f.writes[0].data.tipos[0],0);});
test('payment includes server version and exact input; does not touch accounting',async()=>{const f=fixture();await f.api.saveMovement('pago');assert.equal(f.writes.length,1);assert.equal(f.writes[0].data.version,3);assert.equal(f.writes[0].data.importe,50);assert.equal(f.writes[0].kind,'pago');});
test('empty payment and missing note rejected before request',async()=>{const f=fixture();f.fields.pmAmount.value='';await f.api.saveMovement('pago');assert.equal(f.writes.length,0);f.fields.pmAmount.value='10';f.fields.pmNote.value='';await f.api.saveMovement('pago');assert.equal(f.writes.length,0);});
test('invoice selection excludes sales and other projects and requires explicit selection',async()=>{const f=fixture();f.api.invoice();assert.match(f.box.innerHTML,/Factura/);assert.doesNotMatch(f.box.innerHTML,/Venta|Ajena/);await f.api.saveInvoice();assert.equal(f.writes.length,0);f.fields.pmInvoice.value='0';await f.api.saveInvoice();assert.equal(f.writes[0].data.asiento,1);});
test('supplier text is escaped',()=>{const f=fixture();assert.match(f.box.innerHTML,/&lt;Proveedor>/);assert.doesNotMatch(f.box.innerHTML,/<Proveedor>/);});
