import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const save=html.slice(html.indexOf('function saveDoc(){'),html.indexOf('const QST ='));
const lookup=html.slice(html.indexOf('function quoteInvoice('),html.indexOf('function renderQuoteTransition('));
function setup(projectId){const state={draft:{kind:'presupuesto',editRef:'P-0001',num:1,brand:'a',clientIdx:0,projectId,lines:[{price:10}],iva:{on:false},irpf:{on:false},date:'2026-09-15'},quotes:[{ref:'P-0001',status:'acc',projectId:1},{ref:'P-0002',projectId:2}],clients:[{name:'Cliente'}],entries:[],catalog:[]};const c={state,ProjectQuotes:{validate(){}},ESTUDIO_ID:'test',_accessRole:'admin',ModernoCatalog:{applyPriceIntents:x=>x},linesSum:()=>10,serie:()=> 'P',toast(){},render(){}};vm.createContext(c);vm.runInContext(save,c);return c;}
test('editing a quote keeps selected project even if another quote already uses it',()=>{const c=setup(2);c.saveDoc();assert.equal(c.state.quotes[0].projectId,2);assert.equal(c.state.quotes[0].status,'acc');assert.equal(c.state.quotes[1].projectId,2);});
test('clearing a project link persists',()=>{const c=setup(null);c.saveDoc();assert.equal(c.state.quotes[0].projectId,null);});
test('conversion requires a saved invoice with explicit reference, never just same project',()=>{const c={state:{invoices:[{brand:'a',projectId:1,legend:'Other'}]}};vm.createContext(c);vm.runInContext(lookup,c);const q={brand:'a',ref:'P-0001',projectId:1};assert.equal(c.quoteInvoice(q),undefined);c.state.invoices.push({brand:'a',legend:'Según presupuesto P-0001'});assert.ok(c.quoteInvoice(q));c.state.invoices=[];assert.equal(c.quoteInvoice(q),undefined);c.state.invoices=[{brand:'a',sourceQuoteRef:'P-0001',legend:'Changed'}];assert.ok(c.quoteInvoice(q));});
test('all inline scripts parse',()=>{for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){if(m[0].includes('application/ld+json'))continue;new vm.Script(m[1]);}});

test('historical conversion allows payment notes without matching longer reference numbers',()=>{const c={state:{invoices:[{brand:'cm',legend:'Según presupuesto PS-0127. Nota de pago posterior'}]}};vm.createContext(c);vm.runInContext(lookup,c);assert.ok(c.quoteInvoice({brand:'cm',ref:'PS-0127'}));assert.equal(c.quoteInvoice({brand:'cm',ref:'PS-012'}),undefined);assert.equal(c.quoteInvoice({brand:'other',ref:'PS-0127'}),undefined);assert.equal(c.quoteInvoice({brand:'cm'}),undefined);c.state.invoices[0].sourceQuoteRef='PS-999';assert.equal(c.quoteInvoice({brand:'cm',ref:'PS-0127'}),undefined);});
