import test from 'node:test';import assert from 'node:assert/strict';import boards from '../app/room-boards.js';import sync from '../app/sync-merge.js';
import fs from 'node:fs';import vm from 'node:vm';
const fixture=()=>({id:1,name:'Sala',sections:[{name:'Muebles',items:[{id:'a',name:'Silla',price:100,cost:60,qty:2,unit:'m',note:'privado',supplier:'privado',img:'storage://archivos/demo',files:['privado']},{id:'b',name:'Alternativa',alt:true},{id:'c',hidden:true}]}]});
test('saved projection excludes costs, notes, files and unselected alternatives',()=>{const r=fixture(),s=boards.capture({name:'P'},r);const str=JSON.stringify(s);assert.doesNotMatch(str,/privado|cost|supplier|Alternativa/);assert.equal(s.room.sections[0].items.length,1);assert.equal(s.room.sections[0].items[0].price,undefined);});
test('site projection omits selling price even when requested',()=>{const s=boards.capture({},fixture(),{audience:'obra',prices:true});assert.equal(s.prices,false);assert.equal(s.room.sections[0].items[0].price,undefined);});
test('revision stays fixed after edits, removal and serialization',()=>{const r=fixture(),s=boards.capture({},r,{prices:true},'revision','2026-09-11');r.sections[0].items[0].price=200;r.sections=[];const restored=JSON.parse(JSON.stringify(s));assert.equal(restored.room.sections[0].items[0].price,100);assert.equal(restored.room.sections[0].items[0].img,'storage://archivos/demo');});
test('fingerprint detects relevant board changes but ignores operational metadata',()=>{const r=fixture(),a=boards.capture({},r);r.sections[0].items[0].cost=900;assert.equal(boards.fingerprint(a),boards.fingerprint(boards.capture({},r)));r.sections[0].items[0].qty=3;assert.notEqual(boards.fingerprint(a),boards.fingerprint(boards.capture({},r)));});
test('concurrent revision append preserves both snapshots and conflicts on replacing one',()=>{const a=boards.capture({},fixture(),{},'a'),b=boards.capture({},fixture(),{},'b'),c=boards.capture({},fixture(),{},'c');assert.equal(sync.mergeSavedData([a],[a,b],[a,c]).length,3);assert.throws(()=>sync.mergeSavedData([a],[{...a,date:'changed1'}],[{...a,date:'changed2'}]));});
test('PDF uses the displayed snapshot, excludes subsequent changes, and stops on identity change',async()=>{
 const p={id:1,rooms:[fixture()]},zone={style:{}},c={crypto,_accessRole:'admin',ESTUDIO_ID:'study',state:{projects:[p],sessionUser:{id:'user'}},getRoom:()=>({p,r:p.rooms[0]}),canView:()=>true,ModernoDaily:{escape:v=>String(v??'')},modal(){},roomBoardContent:(p,r)=>JSON.stringify(r),document:{getElementById:()=>zone}};let printed=0;c.printAs=async()=>{printed++;return true;};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../app/room-boards.js',import.meta.url),'utf8'),c);c.RoomBoards.open();p.rooms[0].sections[0].items[0].name='Posterior';await c.RoomBoards.pdf();assert.equal(printed,1);assert.doesNotMatch(zone.innerHTML,/Posterior|privado|cost/);c.ESTUDIO_ID='other';await c.RoomBoards.pdf();assert.equal(printed,1);
});
