import test from 'node:test';import assert from 'node:assert/strict';import spec from '../app/specifications.js';import {readFileSync} from 'node:fs';import vm from 'node:vm';import sync from '../app/sync-merge.js';
const html=readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const fixture=()=>({id:1,rooms:[{id:2,sections:[{name:'A',items:[{id:7,name:'Silla',price:100,cost:80,qty:1,files:[{data:'storage://archivos/demo'}]},{id:7,name:'Silla',price:200,cost:150,qty:2}]}]}],pres:[{pages:[{els:[{t:'prod',rid:2,rsi:0,rii:1}]}]}]});
test('prepare binds legacy duplicate products by location, not name or master id; repeat is idempotent',()=>{const p=fixture();let n=0;spec.prepare(p,()=>`id${++n}`);const ref=p.pres[0].pages[0].els[0];assert.equal(spec.resolve(p,ref).item.price,200);const before=JSON.stringify(p);spec.prepare(p);assert.equal(JSON.stringify(p),before);assert.deepEqual(p.rooms[0].sections[0].items[0].files,[{data:'storage://archivos/demo'}]);});
test('presentation follows product through reorder and never targets a neighbour after deletion',()=>{const p=fixture();spec.prepare(p);const ref=p.pres[0].pages[0].els[0],items=p.rooms[0].sections[0].items;items.reverse();spec.reindex(p);assert.equal(ref.rii,0);assert.equal(spec.resolve(p,ref).item.price,200);items.shift();spec.reindex(p);assert.equal(ref.rii,-1);assert.equal(spec.resolve(p,ref),null);});
test('old client dropping an id cannot cause fallback to an unrelated product',()=>{const p=fixture();spec.prepare(p);const ref=p.pres[0].pages[0].els[0];delete p.rooms[0].sections[0].items[1].id;assert.equal(spec.resolve(p,ref),null);});
test('product snapshots, quantities and attachments are independent',()=>{const master={id:8,name:'Sofa',price:100,cost:0,qty:0,files:[{name:'Ficha'}]};const a=spec.fromProduct(master),b=spec.fromProduct(master);assert.notEqual(a.id,b.id);assert.equal(a.libId,8);assert.equal(a.qty,0);a.price=200;a.files[0].name='Proyecto';assert.equal(master.price,100);assert.equal(b.price,100);assert.equal(master.files[0].name,'Ficha');});
test('copies have distinct instance identities and no inherited client decision',()=>{const a={id:'a',libId:8,cli:'ok',cliNote:'sí',rejected:true,status:'Instalado',cost:50};const b=spec.duplicate(a);assert.notEqual(a.id,b.id);assert.equal(b.libId,8);assert.equal(b.cli,undefined);assert.equal(b.status,'Revisión Cliente');assert.equal(a.cli,'ok');});
test('board uses an allowlist, excludes hidden alternatives, and has no read side effects',()=>{const room={sections:[{name:'Salón',items:[{name:'A',cost:90,margin:10,note:'privada',supplier:'privado',files:[{secret:1}],price:100},{name:'oculto',hidden:true},{name:'alternativa',alt:true}]}]};const before=JSON.stringify(room),out=spec.board(room);assert.equal(JSON.stringify(room),before);assert.equal(out[0].items.length,1);assert.equal(out[0].items[0].cost,undefined);assert.equal(out[0].items[0].note,undefined);assert.equal(out[0].items[0].files,undefined);});
test('economics distinguish unknown, free and loss; zero selling price has no percentage',()=>{assert.equal(spec.economics({price:100,cost:null,qty:1}).gain,null);assert.equal(spec.economics({price:100,cost:0,qty:2}).gain,200);assert.equal(spec.economics({price:100,cost:120,qty:2}).gain,-40);assert.equal(spec.economics({price:0,cost:20,qty:1}).margin,null);});
test('concurrent edits retain separate changes and reject reorder conflicts',()=>{const p=fixture();spec.prepare(p);const b=p.rooms[0].sections[0].items,l=structuredClone(b),r=structuredClone(b);l[0].qty=4;r[1].price=300;const out=sync.mergeSavedData(b,l,r);assert.equal(out[0].qty,4);assert.equal(out[1].price,300);assert.throws(()=>sync.mergeSavedData(b,[...l].reverse(),r));});
test('master and project edits no longer propagate into each other',()=>{const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function syncFromLibrary('),html.indexOf('function unitSum(')),c);assert.equal(c.syncFromLibrary({}),false);assert.equal(c.syncToLibrary({}),false);});
test('fake integrations are unavailable and URL helpers do not invent prices',()=>{assert.doesNotMatch(html,/<button[^>]*data-view="integraciones"/);assert.doesNotMatch(html,/Math\.random\(\)\*28/);assert.doesNotMatch(html,/Clasificado por IA/);const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function canView('),html.indexOf('function applyRoleNav(')),c);assert.equal(c.canView('integraciones'),false);});
test('duplicate generated identity fails without partial conversion',()=>{const p=fixture(),before=JSON.stringify(p);assert.throws(()=>spec.prepare(p,()=> 'same'));assert.equal(JSON.stringify(p),before);});
test('collaborator edits cannot rebind server protected legacy identities',()=>{const c={_accessRole:'colaborador',ModernoSpec:{prepare(){throw Error('must not run')}}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function specPrepare('),html.indexOf('function specInsertPresentation(')),c);assert.equal(c.specPrepare({}),false);});
test('URL suggestions preserve checked fields and do not create products or prices',()=>{const fields={u:{value:'https://example.invalid/sofa-beige'},n:{value:'Nombre revisado'},cat:{value:'Otros'}};const c={URL,document:{getElementById:k=>fields[k]},aiCategory:()=> 'Mobiliario',toast(){}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function productUrlSuggest('),html.indexOf('function mgAuto(')),c);c.productUrlSuggest('u','n','cat');assert.equal(fields.n.value,'Nombre revisado');assert.equal(fields.cat.value,'Mobiliario');assert.doesNotMatch(html,/IMP_SAMPLES/);});
test('upload completion after closing cannot populate a subsequent product editor',async()=>{let release;const old={form:{isConnected:true},files:[],pending:0};const c={itemUploadDraft:old,fileUp:()=>new Promise(r=>release=r),itDrawFiles(){throw Error('closed form');}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function itemDraftActive('),html.indexOf('function itDrawThumb(')),c);const work=c.itAddFiles([{name:'demo.pdf',type:'application/pdf'}]);old.form.isConnected=false;c.itemUploadDraft={form:{isConnected:true},files:[],pending:0};release('storage://archivos/demo.pdf');await work;assert.equal(old.files.length,0);assert.equal(c.itemUploadDraft.files.length,0);assert.equal(old.pending,0);});
test('product file attachment retains content and metadata',async()=>{const d={form:{isConnected:true},files:[],pending:0};const c={itemUploadDraft:d,fileUp:async()=> 'storage://archivos/demo.pdf',itDrawFiles(){}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function itemDraftActive('),html.indexOf('function itDrawThumb(')),c);await c.itAddFiles([{name:'demo.pdf',type:'application/pdf'}]);assert.equal(d.files[0].data,'storage://archivos/demo.pdf');assert.equal(d.files[0].name,'demo.pdf');assert.equal(d.pending,0);});
test('moodboard link follows the same identity after JSON roundtrip and section reorder',()=>{const p=fixture();p.moods=[{secs:[{items:[{prodRef:{rid:2,rsi:0,rii:1}}]}]}];spec.prepare(p);const restored=JSON.parse(JSON.stringify(p));restored.rooms[0].sections.unshift({name:'Nueva',items:[]});spec.reindex(restored);const ref=restored.moods[0].secs[0].items[0].prodRef;assert.equal(ref.rsi,1);assert.equal(spec.resolve(restored,ref).item.price,200);});
test('missing cost is not synthesized by simply opening the editor',()=>{const c={};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function mgAuto('),html.indexOf('function mgUI(')),c);assert.equal(c.mgAuto({cost:null,price:100}),undefined);assert.match(html,/const libre = cur==="libre" \|\| cur===null \|\| cur===undefined/);});
test('board markup escapes product content and has no costs or notes',()=>{const c={ModernoSpec:spec,ModernoDaily:{escape:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')},fmt:n=>n+' EUR',fileImageAttrs:()=>''};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function roomBoardContent('),html.indexOf('function roomBoard(){')),c);const result=c.roomBoardContent({num:'P',name:'Demo'},{name:'Sala',sections:[{name:'General',items:[{name:'<script>bad</script>',price:100,cost:99999,note:'nota privada',qty:1}]}]},false);assert.match(result,/&lt;script>/);assert.doesNotMatch(result,/<script>|99999|nota privada|100 EUR/);});


test('batch room copies have distinct compatible IDs and independent product identities',()=>{const c={ModernoSpec:spec,crypto,state:{projects:[]},Date:{now:()=>1000}};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function roomCloneData('),html.indexOf('function roomToProjectModal(')),c);const room={id:1,shareToken:'private',sections:[{items:[{id:1,name:'Silla',cli:'ok'}]}]};const copies=Array.from({length:100},()=>c.roomCloneData(room,-1));assert.equal(new Set(copies.map(r=>r.id)).size,100);assert.equal(new Set(copies.map(r=>r.sections[0].items[0].id)).size,100);assert.equal(copies[0].shareToken,undefined);assert.equal(room.sections[0].items[0].cli,'ok');});
