import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
const legacy=execFileSync('git',['show','c91d243:app/index.html'],{encoding:'utf8',maxBuffer:3e6});
const current=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const section=(s,a,b)=>s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));
const oldFlush=section(legacy,'async function cloudFlush(){','function cloudSnapshotAll(){');
const oldPersist=section(legacy,'function persistNow(){','/* v3.28:');
const oldExport=section(legacy,'function backupExport(){','function backupImport(');
const keep=section(current,'function cloudKeepPendingCopy(){','function cloudPendingNotice(){');
function fixture({quota=false}={}){
 const base=[{id:1,name:'Versión anterior'}],edited=[{id:1,name:'Cambio local ficticio'}],map=new Map();map.set('test',JSON.stringify({v:1,state:{projects:base}}));map.set('test_dirty','1');let exported='',writes=0;
 const c={Date,JSON,encodeURIComponent,console:{info(){},warn(){}},state:{projects:edited},BRAND:{},wsOrder:[],LS_KEY:'test',ESTUDIO_ID:'ficticio',_resumed:true,_lastSave:null,_saveErr:false,_cloudBusy:false,_cloudApplying:false,_cloudHash:{proyectos:JSON.stringify(base)},_cloudSeen:{proyectos:'2026-09-09T00:00:00Z'},_cloudCount:{proyectos:1},_cloudForce:{},_cloudRetryT:null,window:{},CLOUD_BLOCKS:{proyectos:{get:()=>edited}},canon:JSON.stringify,blockCount:v=>v.length,syncTag(mode){c.mode=mode},toast(){},cloudDirty(){map.set('test_dirty','1')},persistSoon(){},tkRefreshFromCloud(){},absorbComments(){return 0},clearTimeout(){},setTimeout(){c.retry=true},localStorage:{getItem:k=>map.get(k)||null,setItem(k,v){if(quota)throw Error('QuotaExceededError');map.set(k,v)},removeItem:k=>map.delete(k)},document:{createElement(){return {href:'',click(){exported=this.href}}}},sb:{from(){return {select(){return this},eq(){return this},async maybeSingle(){return {data:{contenido:base,updated_at:'2026-09-09T00:00:00Z'}}},async upsert(){writes++;return {error:{code:'42501',message:'permission denied'}}}}}}};
 vm.createContext(c);vm.runInContext(oldFlush+'\n'+oldPersist+'\n'+oldExport+'\n'+keep,c);return {c,map,base,edited,exported:()=>JSON.parse(decodeURIComponent(exported.split(',').slice(1).join(','))),writes:()=>writes};
}
test('legacy client denied by write gate keeps pending data and schedules retry',async()=>{const f=fixture();f.c.persistNow();await f.c.cloudFlush();assert.equal(f.writes(),1);assert.equal(f.c.mode,'err');assert.equal(f.map.get('test_dirty'),'1');assert.equal(f.c._cloudHash.proyectos,JSON.stringify(f.base));assert.equal(JSON.parse(f.map.get('test')).state.projects[0].name,'Cambio local ficticio');assert.equal(f.c.retry,true);});
test('legacy export with healthy local storage carries changes into candidate pending copy',()=>{const f=fixture();f.c.backupExport();assert.equal(f.exported().state.projects[0].name,'Cambio local ficticio');f.c.cloudKeepPendingCopy();const key=[...f.map.keys()].find(k=>k.startsWith('test_pendiente_'));assert.ok(key);assert.equal(JSON.parse(f.map.get(key)).state.projects[0].name,'Cambio local ficticio');assert.equal(f.map.has('test_dirty'),false);});
test('known legacy hazard: quota failure can export stale data, so transition must stop',()=>{const f=fixture({quota:true});f.c.backupExport();assert.equal(f.c._saveErr,true);assert.equal(f.c.state.projects[0].name,'Cambio local ficticio');assert.equal(f.exported().state.projects[0].name,'Versión anterior');});
test('candidate refuses to clear dirty state when pending copy cannot be preserved',()=>{const f=fixture({quota:true});assert.throws(()=>f.c.cloudKeepPendingCopy());assert.equal(f.map.get('test_dirty'),'1');assert.equal(f.c.state.projects[0].name,'Cambio local ficticio');});
