import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../app/workflow-polish.js',import.meta.url),'utf8');
function setup(){let writes=0;const c=vm.createContext({state:{account:{},customCats:['Luz','Muebles'],library:[],sessionUser:{id:'a'}},ESTUDIO_ID:'one',_accessRole:'admin',persistSoon(){writes++},render(){},document:{activeElement:null},V:{querySelectorAll:()=>[]},matchMedia:()=>({matches:true}),fmt:n=>String(n)});vm.runInContext(source+';globalThis.api=WorkflowPolish',c);return {c,api:c.api,writes:()=>writes};}
test('category order persists in account and refuses non-admin changes',()=>{const {c,api,writes}=setup();api.categoryMove('Muebles',0);assert.deepEqual(JSON.parse(JSON.stringify(c.state.account.libraryCategoryOrder)),['Muebles','Luz']);assert.equal(writes(),1);c._accessRole='member';api.categoryMove('Luz',0);assert.equal(writes(),1);c.state.account={};assert.equal(api.categoryOrder(['Muebles','Luz'])[0],'Luz');});
test('forecast filters accents and month without modifying payment rows',()=>{const {api}=setup();const rows=[{p:{name:'Reforma Ático'},h:{concept:'Entrega',due:'2026-09-21',amount:15}},{p:{name:'Reforma Ático'},h:{concept:'Entrega',due:'2026-10-21',amount:20}}];const before=JSON.stringify(rows);api.forecastChange('month','2026-09');api.forecastChange('q','atico');assert.equal(api.forecastRows(rows).length,1);assert.equal(JSON.stringify(rows),before);api.forecastChange('anchor','2026-10-01');assert.equal(api.forecastRows(rows)[0].h.amount,20);});
test('forecast preferences isolated by study and day calendar contains one date',()=>{const {api,c}=setup();api.forecastChange('view','dia');api.forecastChange('anchor','2026-09-21');const html=api.forecastCalendar([]);assert.equal((html.match(/<section /g)||[]).length,1);assert.match(html,/forecast-calendar-scroll/);c.ESTUDIO_ID='two';assert.equal(api.forecastState().view,'lista');assert.equal(api.forecastState().q,'');});
test('all inline scripts compile with the new navigation helpers',()=>{const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');for(const m of html.matchAll(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
