import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import daily from '../app/daily-work.js';
const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const code=html.slice(html.indexOf('function wsViewKey(){'),html.indexOf('function wsDrop('));
function fixture(){const map=new Map();const c={ModernoDaily:daily,LS_KEY:'test',meMail:()=> 'ana@example.invalid',localStorage:{getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)},render(){},toast(){},APP_LOCALE:()=> 'es-ES',taskAssignees:t=>t.who||[],KCOLS:[['pend','Pendientes']],dailyDue:t=>daily.due(t.due).label};vm.createContext(c);vm.runInContext(code,c);return {c,map};}
test('month grid starts Monday and includes leap day exactly once',()=>{const days=daily.monthDays('2024-02');assert.equal(days.indexOf('2024-02-01'),3);assert.equal(days.filter(Boolean).length,29);assert.equal(new Set(days.filter(Boolean)).size,29);assert.equal(days.length%7,0);});
test('month boundaries exclude impossible dates and reject malformed month',()=>{assert.equal(daily.monthDays('2026-02').filter(Boolean).length,28);assert.equal(daily.monthDays('2026-12').filter(Boolean).at(-1),'2026-12-31');assert.throws(()=>daily.monthDays('2026-13'));});
test('view preference is separated by identity and cannot change shared state',()=>{const {c,map}=fixture();assert.equal(c.wsViewGet(),'tablero');c.wsViewSet('lista');assert.equal(c.wsViewGet(),'lista');c.meMail=()=> 'otro@example.invalid';assert.equal(c.wsViewGet(),'tablero');c.wsViewSet('unknown');assert.equal(map.size,1);});
test('list and calendar preserve source and exact original task index',()=>{const {c}=fixture();const cards=[{p:{id:12,num:'PR-1',name:'Ficticio'},i:7,t:{title:'<Tarea>',due:'2026-09-09',col:'pend'}},{p:{id:12,num:'PR-1',name:'Ficticio'},i:9,t:{title:'Sin fecha',due:'',col:'pend'}}];const before=JSON.stringify(cards);vm.runInContext("_wsCalendarMonth='2026-09'",c);for(const result of [c.wsList(cards),c.wsCalendar(cards)]){assert.match(result,/openDailyTask\(12,7\)/);assert.match(result,/openDailyTask\(12,9\)/);assert.ok(!result.includes('<Tarea>'));}assert.equal(JSON.stringify(cards),before);});
test('calendar accounts for other months and invalid dates without duplicating tasks',()=>{const {c}=fixture();vm.runInContext("_wsCalendarMonth='2026-09'",c);const cards=['2026-09-09','2026-10-01','bad'].map((due,i)=>({p:{id:1,num:'P',name:'F'},i,t:{due,title:'T'+i}}));const result=c.wsCalendar(cards);assert.match(result,/1 tareas en este mes · 1 en otros meses · 1 sin fecha/);assert.equal((result.match(/openDailyTask\(1,0\)/g)||[]).length,1);assert.equal((result.match(/openDailyTask\(1,2\)/g)||[]).length,1);assert.ok(!result.includes('openDailyTask(1,1)'));});
